### ISSUE TITLE
Can't install howdoi

### ISSUE THREAD

**Issue by aalexgabi** [gleitz/howdoi#101]
I tried:
```
pip install howdoi
```
Also:
```
pip3 install howdoi
```
And:
```
pip install git+https://github.com/gleitz/howdoi.git#egg=howdoi
```
They both fail with:
```
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_alex/howdoi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xitgET-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_alex/howdoi
Storing debug log for failure in /home/alex/.pip/pip.log
```
/home/alex/.pip/pip.log ends with:
```
----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_alex...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_alex/howdoi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xitgET-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_alex/howdoi
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_alex/howdoi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xitgET-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_alex/howdoi
```

**Comment by h-2-0** [comment]
Hi!

I can't install it in neither Python2.6 nor Python3.2

sudo pip install howdoi / sudo pip-2.7 install howdoi
or 
pip install howdoi 
or
pip install git+https://github.com/gleitz/howdoi.git#egg=howdoi

I also tried it using pip-2.7 and with or without sudo.


This is the error message I'm getting when installer uses Python3.2:

command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_rodo/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-35_56i-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_rd/lxml

**Comment by ncrocfer** [comment]
I think it's a problem with the `lxml` dependencies. See this [answer](http://stackoverflow.com/questions/26291396/fail-to-install-lxml-using-pip?answertab=votes#tab-top) on StackOverflow.
To install it :

`$ sudo apt-get install libxml2-dev libxslt-dev  python-dev  python-setuptools`
`$ sudo pip install lxml`

**Comment by h-2-0** [comment]
Thanks, ncrocfer! It worked for Python 2.7 but something went wrong when installing to Python3.2!

So i did: 
$ sudo apt-get install libxml2-dev libxslt-dev python-dev python-setuptools
$ sudo pip install lxml
$ sudo pip install howdoi
$ howdoi whatever

Traceback (most recent call last):
  File "/usr/local/bin/howdoi", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cssselect

So then I did 

$ sudo pip-2.7 install howdoi
# ...
# Successfully installed lxml cssselect
$ howdoi whatever
Sorry, couldn't find any help with that topic
 
It worked!
