### ISSUE TITLE
Crash while trying to print utf-encoded answer in non-utf locale on Windows

### ISSUE THREAD

**Issue by uppi** [gleitz/howdoi#107]
subj
![d9930d0ba2da75ce3ebf6d55e999852f](https://cloud.githubusercontent.com/assets/1144071/6801049/8d5a29f6-d235-11e4-8661-916b61789661.png)

**Comment by gleitz** [comment]
The Windows application is very old. Perhaps you can generate a new version? (it was done by a generous contributor long ago)
