### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by int32at** [gleitz/howdoi#108]
whenever i try to get some results i receive this error message twice before i get the actual answer

> /Library/Python/2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

any ideas what that could be?

thanks!

**Comment by colincrossland** [comment]
From the link :

Certain Python platforms (specifically, versions of Python earlier than 2.7.9) have restrictions in their ssl module that limit the configuration that urllib3 can apply. In particular, this can cause HTTPS requests that would succeed on more featureful platforms to fail, and can cause certain security features to be unavailable.

If you encounter this warning, it is strongly recommended you upgrade to a newer Python version, or that you use pyOpenSSL as described in the OpenSSL / PyOpenSSL section.

**Comment by int32at** [comment]
thanks for the answer, fixed it now ;)
