### ISSUE TITLE
Insecure platform warning on Fedora 19

### ISSUE THREAD

**Issue by nickodell** [gleitz/howdoi#110]
On the first two invocations of howdoi, I got this warning:

    /usr/lib/python2.7/site-packages/requests-2.6.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
     InsecurePlatformWarning

[This page](https://urllib3.readthedocs.org/en/latest/security.html) discusses ways to enable the check or disable the warning.

**Comment by MinimaxHeadroom** [comment]
Happens similarly on Mac OS X Yosemite. Invoke howdoi results in two separate such warnings.

**Comment by colincrossland** [comment]
What version of python are you using? This message come up if you use <2.7.9 due to restrictions in the ssl module. Easy fix is to upgradeto >=2.7.9

**Comment by MinimaxHeadroom** [comment]
Python 2.7.9, that's right. Thanks for the reply, will consider upgrading
