### ISSUE TITLE
Exception for certain queries using Python 2.9

### ISSUE THREAD

**Issue by giacomocusinato** [gleitz/howdoi#111]
I get an exception for certain queries, like the one that follows:

![hoedoi_exception](https://cloud.githubusercontent.com/assets/7659518/6907749/1ef3b42e-d739-11e4-97d2-59fb731a351e.png)

I get this error just using Python 2.9, with Python 3.4 works just fine.
This block of code is the one throwing the exception:

```python
try:
        return requests.get(url, headers={'User-Agent': random.choice(USER_AGENTS)}, proxies=get_proxies()).text
    except requests.exceptions.SSLError as e:
        print('[ERROR] Encountered an SSL Error. Try using HTTP instead of '
              'HTTPS by setting the environment variable "HOWDOI_DISABLE_SSL".\n')
        raise e
`
``

Using `urllib2` module instead `requests` could solve the problem. I'll try to submit a pull request.

**Comment by gleitz** [comment]
I would rather keep the requests library. If there are issues with it please report them to https://github.com/kennethreitz/requests
