### ISSUE TITLE
InsecurePlatformWarning

### ISSUE THREAD

**Issue by aaronharding** [gleitz/howdoi#118]
After running "howdoi x" I'm greeting with this before the answer appears:

> /Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may
>  cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
>  InsecurePlatformWarning
> /Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may
> cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
>  InsecurePlatformWarning

I installed it manually by cloning down the repo and running setup.py install. wat do?

**Comment by idf** [comment]
Try to update to 2.7.9. This is an issue related to Python.

**Comment by idf** [comment]
Encounter same problem. `pip install requests[security]` solves my problem.

**Comment by aaronharding** [comment]
Whoa yeah, `sudo pip install requests[security]` solved this too. Thanks!
