### ISSUE TITLE
Introducing slack-howdoi

### ISSUE THREAD

**Issue by ellisonleao** [gleitz/howdoi#119]
Hey guys, i just finish up a Slack integration with this awesome library.

https://github.com/ellisonleao/slack-howdoi

Can we add a mention on that on README, perhaps? Please let me know what you think.

**Comment by gleitz** [comment]
Very cool! Yes – I'll add this to the README. Do you expect `https://slack-howdoi.herokuapp.com/` to continue running indefinitely? A cron job pulling the latest `howdoi` package from pip would be slick.

**Comment by ellisonleao** [comment]
For now yes @gleitz , i can do the cron job if you want too! Thanks for the feedback!

**Comment by gleitz** [comment]
https://github.com/gleitz/howdoi/commit/67e9c7d383de0755d39d0c16750f8fdec061513d
