### ISSUE TITLE
cannot install with homebrew, it complains about python

### ISSUE THREAD

**Issue by iamstarkov** [gleitz/howdoi#120]
but I’m have python installed on my machine. And also update to 2.7.10 to verify, that it’s not the same issue as #114.

So it’s strange that it’s not going to work 😟

    ➜  ~  brew --version
    0.9.5
    ➜  ~  python --version
    Python 2.7.10

I’m not sure if it all required information to debug, so feel free to point me out what you need for more investigation and reproducing

**Comment by gleitz** [comment]
Please include a stack trace of the install issue and then re-open.
