### ISSUE TITLE
InsecurePlatformWarning: howdoi returns no result

### ISSUE THREAD

**Issue by damilare** [gleitz/howdoi#121]
On installation on Osx Yosemite in a virtualenv, I get the following error.

python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You will need to install the "office.dll" library in the Global Assembly Cache on the server too to make this work. Check out the C:\Windows\assembly folder and you will find office.dll there. EDIT:
It seems that this will not be as simple as it looks. Some developers mention here that Office would have to be installed on the server or you will need to install even more libraries manually.

**Comment by Chakerbh** [comment]
This issue has been discussed before  #118

**Comment by blakejennings** [comment]
Hey @damilare, ```pip install pyopenssl ndg-httpsclient pyasn1``` fixed the issue for me.
