### ISSUE TITLE
Not working on pypy3-2.4.0

### ISSUE THREAD

**Issue by pathcl** [gleitz/howdoi#129]
pathcl@sid:~/src/introducing-python$ pip install howdoi
Collecting howdoi
  Using cached howdoi-1.1.7.tar.gz
Collecting pyquery (from howdoi)
  Using cached pyquery-1.2.9.zip
Requirement already satisfied (use --upgrade to upgrade): pygments in /home/pathcl/.pyenv/versions/pypy3-2.4.0/site-packages (from howdoi)
Requirement already satisfied (use --upgrade to upgrade): requests in /home/pathcl/.pyenv/versions/pypy3-2.4.0/site-packages (from howdoi)
Collecting requests-cache (from howdoi)
  Using cached requests-cache-0.4.10.tar.gz
Collecting lxml>=2.1 (from pyquery->howdoi)
  Using cached lxml-3.4.4.tar.gz
Collecting cssselect (from pyquery->howdoi)
  Using cached cssselect-0.9.1.tar.gz
Building wheels for collected packages: howdoi, pyquery, requests-cache, lxml, cssselect
  Running setup.py bdist_wheel for howdoi
  Stored in directory: /home/pathcl/.cache/pip/wheels/fe/dd/9c/a932eb5826349d856c23e9446c90cf06fd5e506c2feb4b745c
  Running setup.py bdist_wheel for pyquery
  Stored in directory: /home/pathcl/.cache/pip/wheels/31/a2/d9/1507d953e62680093163139ab6222f1ed408e9290abfa5bd67
  Running setup.py bdist_wheel for requests-cache
  Stored in directory: /home/pathcl/.cache/pip/wheels/c9/3d/a1/5947d1ed492d661749cac157f20b8a7f5df6961a62d1df0168
  Running setup.py bdist_wheel for lxml
  Complete output from command /home/pathcl/.pyenv/versions/pypy3-2.4.0/bin/python -c "import setuptools;__file__='/tmp/pip-build-eq5arr/lxml/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpm9h6_lpip-wheel-:
  Building lxml version 3.4.4.
  Building without Cython.
  Using build configuration of libxslt 1.1.28
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.2
  creating build/lib.linux-x86_64-3.2/lxml
  copying src/lxml/sax.py -> build/lib.linux-x86_64-3.2/lxml
  copying src/lxml/builder.py -> build/lib.linux-x86_64-3.2/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-3.2/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-3.2/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-x86_64-3.2/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-3.2/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-3.2/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-3.2/lxml
  copying src/lxml/__init__.py -> build/lib.linux-x86_64-3.2/lxml
  creating build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-3.2/lxml/includes
  creating build/lib.linux-x86_64-3.2/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-3.2/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-3.2/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-x86_64-3.2/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-x86_64-3.2/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-3.2/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-3.2/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-3.2/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-3.2/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-x86_64-3.2/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-3.2/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-3.2/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-3.2/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-x86_64-3.2/lxml/html
  creating build/lib.linux-x86_64-3.2/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-3.2/lxml/isoschematron
  copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-3.2/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-3.2/lxml
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-3.2/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-3.2/lxml/includes
  creating build/lib.linux-x86_64-3.2/lxml/isoschematron/resources
  creating build/lib.linux-x86_64-3.2/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-3.2/lxml/isoschematron/resources/rng
  creating build/lib.linux-x86_64-3.2/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-3.2/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-3.2/lxml/isoschematron/resources/xsl
  creating build/lib.linux-x86_64-3.2/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-3.2/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-3.2/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-3.2/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-3.2/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-3.2/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-3.2/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-x86_64-3.2
  creating build/temp.linux-x86_64-3.2/src
  creating build/temp.linux-x86_64-3.2/src/lxml
  cc -O2 -fPIC -Wimplicit -I/usr/include/libxml2 -I/tmp/pip-build-eq5arr/lxml/src/lxml/includes -I/home/pathcl/.pyenv/versions/pypy3-2.4.0/include -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-3.2/src/lxml/lxml.etree.o -w
  cc -shared build/temp.linux-x86_64-3.2/src/lxml/lxml.etree.o -lxslt -lexslt -lxml2 -lz -lm -o build/lib.linux-x86_64-3.2/lxml/etree.pypy3-24.so
  building 'lxml.objectify' extension
  cc -O2 -fPIC -Wimplicit -I/usr/include/libxml2 -I/tmp/pip-build-eq5arr/lxml/src/lxml/includes -I/home/pathcl/.pyenv/versions/pypy3-2.4.0/include -c src/lxml/lxml.objectify.c -o build/temp.linux-x86_64-3.2/src/lxml/lxml.objectify.o -w
  src/lxml/lxml.objectify.c:30412:3: error: ‘__pyx_pw_4lxml_9objectify_13NumberElement_29__div__’ undeclared here (not in a function)
     __pyx_pw_4lxml_9objectify_13NumberElement_29__div__, /*nb_divide*/
     ^
  src/lxml/lxml.objectify.c:30484:3: error: ‘__pyx_pw_4lxml_9objectify_13NumberElement_5__long__’ undeclared here (not in a function)
     __pyx_pw_4lxml_9objectify_13NumberElement_5__long__, /*nb_long*/
     ^
  src/lxml/lxml.objectify.c:30498:3: error: ‘__pyx_pw_4lxml_9objectify_13NumberElement_15__oct__’ undeclared here (not in a function)
     __pyx_pw_4lxml_9objectify_13NumberElement_15__oct__, /*nb_oct*/
     ^
  src/lxml/lxml.objectify.c:30505:3: error: ‘__pyx_pw_4lxml_9objectify_13NumberElement_17__hex__’ undeclared here (not in a function)
     __pyx_pw_4lxml_9objectify_13NumberElement_17__hex__, /*nb_hex*/
     ^
  /home/pathcl/.pyenv/versions/pypy3-2.4.0/lib-python/3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  error: command 'cc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py bdist_wheel for cssselect
  Stored in directory: /home/pathcl/.cache/pip/wheels/c6/0e/79/ae69bf7b31029e0f0bc5b8306547f94ec3926b7dbb8452b5ea
Successfully built howdoi pyquery requests-cache cssselect
Failed to build lxml
Installing collected packages: lxml, cssselect, pyquery, requests-cache, howdoi
  Running setup.py install for lxml
    Complete output from command /home/pathcl/.pyenv/versions/pypy3-2.4.0/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-eq5arr/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-n6dk55-record/install-record.txt --single-version-externally-managed --compile:
    Building lxml version 3.4.4.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    running install
    running build
    running build_py
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-3.2/lxml/includes
    running build_ext
    building 'lxml.objectify' extension
    cc -O2 -fPIC -Wimplicit -I/usr/include/libxml2 -I/tmp/pip-build-eq5arr/lxml/src/lxml/includes -I/home/pathcl/.pyenv/versions/pypy3-2.4.0/include -c src/lxml/lxml.objectify.c -o build/temp.linux-x86_64-3.2/src/lxml/lxml.objectify.o -w
    src/lxml/lxml.objectify.c:30412:3: error: ‘__pyx_pw_4lxml_9objectify_13NumberElement_29__div__’ undeclared here (not in a function)
       __pyx_pw_4lxml_9objectify_13NumberElement_29__div__, /*nb_divide*/
       ^
    src/lxml/lxml.objectify.c:30484:3: error: ‘__pyx_pw_4lxml_9objectify_13NumberElement_5__long__’ undeclared here (not in a function)
       __pyx_pw_4lxml_9objectify_13NumberElement_5__long__, /*nb_long*/
       ^
    src/lxml/lxml.objectify.c:30498:3: error: ‘__pyx_pw_4lxml_9objectify_13NumberElement_15__oct__’ undeclared here (not in a function)
       __pyx_pw_4lxml_9objectify_13NumberElement_15__oct__, /*nb_oct*/
       ^
    src/lxml/lxml.objectify.c:30505:3: error: ‘__pyx_pw_4lxml_9objectify_13NumberElement_17__hex__’ undeclared here (not in a function)
       __pyx_pw_4lxml_9objectify_13NumberElement_17__hex__, /*nb_hex*/
       ^
    /home/pathcl/.pyenv/versions/pypy3-2.4.0/lib-python/3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/home/pathcl/.pyenv/versions/pypy3-2.4.0/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-eq5arr/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-n6dk55-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-eq5arr/lxml

**Comment by gleitz** [comment]
Looks like an lxml issue...would you please raise the issue with [them](https://github.com/lxml/lxml/)?
