### ISSUE TITLE
No module named howdoi.howdoi

### ISSUE THREAD

**Issue by bharadwaj-raju** [gleitz/howdoi#130]
Whenever I run howdoi, it shows:

    Traceback (most recent call last):
      File "/usr/local/bin/howdoi", line 9, in <module>
        load_entry_point('howdoi==1.1.7', 'console_scripts', 'howdoi')()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
        return ep.load()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
        entry = __import__(self.module_name, globals(),globals(), ['__name__'])
    ImportError: No module named howdoi.howdoi`

**Comment by gleitz** [comment]
Please provide more information about your environment to help troubleshoot.

- What version of Python?
- What OS?
- How did you install?
- What command are you typing?

If you installed using `pip` you should be able to type `howdoi QUERY`.

If you cloned the source, you should be able to go into the howdoi directory and type `python -m howdoi.howdoi QUERY`

**Comment by bharadwaj-raju** [comment]
I cloned the github repo.

Python version: 2.7.6

OS: Linux

Installation: `sudo setup.py install`

Command: `howdoi`

**Comment by gleitz** [comment]
Please try installing with pip and let me know if you're still having
issues.

**Comment by bharadwaj-raju** [comment]
`pip install howdoi`

Reports as already installed.

Full output:

    $ pip install howdoi
    Requirement already satisfied (use --upgrade to upgrade): howdoi in /usr/local/lib/python2.7/dist-packages/howdoi-1.1.7-py2.7.egg
    Requirement already satisfied (use --upgrade to upgrade): pyquery in /usr/local/lib/python2.7/dist-packages/pyquery-1.2.9-py2.7.egg (from howdoi)
    Requirement already satisfied (use --upgrade to upgrade): pygments in /usr/local/lib/python2.7/dist-packages/Pygments-2.0.2-py2.7.egg (from howdoi)
    Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from howdoi)
    Requirement already satisfied (use --upgrade to upgrade): requests-cache in /usr/local/lib/python2.7/dist-packages/requests_cache-0.4.10-py2.7.egg (from howdoi)
    Requirement already satisfied (use --upgrade to upgrade): lxml>=2.1 in /usr/lib/python2.7/dist-packages (from pyquery->howdoi)
    Requirement already satisfied (use --upgrade to upgrade): cssselect in /usr/local/lib/python2.7/dist-packages/cssselect-0.9.1-py2.7.egg (from pyquery->howdoi)
    Cleaning up...

Same with `sudo`.

**Comment by bharadwaj-raju** [comment]
In the source directory (howdoi-master/howdoi), I did (as you said) `python -m howdoi.howdoi format date bash`.

Output:

    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
      File "/usr/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
      File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
      File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
      File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
      File "howdoi.py", line 19, in <module>
    from . import __version__
    ValueError: Attempted relative import in non-package

`

**Comment by gleitz** [comment]
You should run the command (`python -m howdoi.howdoi format date bash`) from the top level directory (`howdoi-master`)

This command looks inside the module named `howdoi` and runs the corresponding `howdoi.py` file as a script, passing the given arguments.

**Comment by bharadwaj-raju** [comment]
Then why did it fail with `pip`?

**Comment by gleitz** [comment]
When you install with `pip` you run `howdoi format date bash`

When you are dealing with the source directly, you use `python -m howdoi.howdoi format date bash`

**Comment by bharadwaj-raju** [comment]
Yes, but installing with `pip` and running the same command gives the `no
module named howdoi.howdoi` error.

--
Bharadwaj
