### ISSUE TITLE
Does not work on latest Virtualbox

### ISSUE THREAD

**Issue by minthemiddle** [gleitz/howdoi#131]
On the latest Virtualbox running Ubuntu 15.04., you cannot run `howdoi`. You always get `Encountered an SSL Error`.

I set the SSL variable to `1`, but the error persists:

```
m@lubuntu1504:~$ export HOWDOI_DISABLE_SSL=1
m@lubuntu1504:~$ echo $HOWDOI_DISABLE_SSL
1
m@lubuntu1504:~$ howdoi export environment variable
[ERROR] Encountered an SSL Error. Try using HTTP instead of HTTPS by setting the environment variable "HOWDOI_DISABLE_SSL".

Failed to establish network connection
```

Accessing HTTPS websites via browser is no problem, so does `curl https//www.google.de`.

There must be something with `howdoi`

**Comment by minthemiddle** [comment]
Eh, some queries work. But I could not find a pattern.

```
m@lubuntu1504:~/Code/howdoi$ howdoi loop dict python
for key in d:

m@lubuntu1504:~/Code/howdoi$ howdoi import json python
[ERROR] Encountered an SSL Error. Try using HTTP instead of HTTPS by setting the environment variable "HOWDOI_DISABLE_SSL".

Failed to establish network connection

m@lubuntu1504:~/Code/howdoi$ howdoi export json
[ERROR] Encountered an SSL Error. Try using HTTP instead of HTTPS by setting the environment variable "HOWDOI_DISABLE_SSL".

Failed to establish network connection

m@lubuntu1504:~/Code/howdoi$ howdoi loop dict python
for key in d:
```

**Comment by gleitz** [comment]
Sounds like you may be getting rate limited by Google? If you view in a browser does it ever give you a captcha?

**Comment by minthemiddle** [comment]
No, I never get any captcha. Everything works as expected in both CLI and the browser. It is just `howdoi` that gives me such an error.

**Comment by gleitz** [comment]
Odd. You can check out the code and run `python -m howdoi.howdoi QUERY` and see where exactly the code fails.

**Comment by gleitz** [comment]
Going to close this for now. Please post the results of running `python -m howdoi.howdoi QUERY` if you want to re-open the issue.
