### ISSUE TITLE
HOWDOI_COLORIZE doesn't automatically set color

### ISSUE THREAD

**Issue by jackmaney** [gleitz/howdoi#134]
I'm using OS X 10.9.5 with `howdoi` version 1.1.7 on Python 3.5.1.

I've enabled the `HOWDOI_COLORIZE` variable in my `.bash_profile`:

```
$ tail -n 1 ~/.bash_profile
export HOWDOI_COLORIZE=1
```

However, setting this doesn't seem to have any effect:

![screen shot 2016-02-22 at 12 22 07 pm](https://cloud.githubusercontent.com/assets/1554625/13228061/5c970c94-d95f-11e5-8421-427eba0c6bd9.png)

Is there something obvious that I'm missing, here?

Thank you for your time.

**Comment by gleitz** [comment]
Looks like the output is colorized, no? The DATE and backticks have color

**Comment by gleitz** [comment]
Ah, I see. The environment variable isn't being used. Feel free to submit a pull request.
