### ISSUE TITLE
Failed to install howdoi with brew

### ISSUE THREAD

**Issue by stonemary** [gleitz/howdoi#147]
> 2015:test doe$ brew install https://raw.github.com/gleitz/howdoi/master/howdoi.rb
######################################################################## 100.0%
==> Downloading http://pypi.python.org/packages/source/h/howdoi/howdoi-1.1.9.tar.gz
==> Downloading from https://pypi.python.org/packages/source/h/howdoi/howdoi-1.1.9.tar.gz

> curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "howdoi"
Download failed: https://pypi.python.org/packages/source/h/howdoi/howdoi-1.1.9.tar.gz

brew version:
>2016:test doe$ brew -v
Homebrew 0.9.5 (git revision 3c89; last commit 2016-03-01)

system: OS X 10.11.4 (15E65)

Thank you!

**Comment by gleitz** [comment]
I updated the URL – please give it a try and let me know if you still have errors
