### ISSUE TITLE
Try using HTTP instead of HTTPS by setting the environment variable "HOWDOI_DISABLE_SSL"

### ISSUE THREAD

**Issue by Gustavo91** [gleitz/howdoi#148]
Hi, I was trying to use howdoi  but i can't because i've this error message:

[Error] Encountered as SSL Error. Try using HTTP instead of HTTPS by setting the environment variable "HOWDOI_DISABLE_SSL"

I have windows 7 and i've already set the environmet variable "HOWDOI_DISABLE_SSL" to 1, but it doesn't work. What can i do?

**Comment by gleitz** [comment]
Are you using Windows? The Windows version is quite old and I'm not sure if it supports HOWDOI_DISABLE_SSL.

I would accept a pull request for a new Windows version if that is something you would like to create.

**Comment by Gustavo91** [comment]
Hi, i would like but i'm still a novice programmer. Thanks anyway man
