### ISSUE TITLE
Warning on brew install

### ISSUE THREAD

**Issue by sbarratt** [gleitz/howdoi#151]
```
Warning: SHA1 support is deprecated and will be removed in a future version.
Please switch this formula to SHA256.
```

**Comment by abhishek7** [comment]
Nice catch @sbarratt, just to add to the issue and give a bit more clarity, please view [https://github.com/Homebrew/brew/issues/606](Homebrew Issue #606)

**Comment by gleitz** [comment]
Thanks!
