### ISSUE TITLE
Snap package for howdoi

### ISSUE THREAD

**Issue by simos** [gleitz/howdoi#157]
I found howdoi useful and I used it to write an article on how to create a snap package,
https://blog.simos.info/how-to-create-a-snap-with-snapcraft-for-howdoi-cli-utilility-for-stackoverflow/

I created a package for howdoi and I uploaded to the Ubuntu Store. 
It can be installed in Ubuntu and other distributions that can run snaps, by running:

snap install howdoi

You may want to add the 'snapcraft.yaml' file (https://gist.github.com/simos/4d498bf773ab23827901c7c9a8015517) in the source directory of howdoi, so that users can also build the snap themselves.

I used the name 'howdoi' for the snap (instead of howdoi.simosx); if you would like to maintain the snap yourself instead, please tell me to transfer ownership of the snap.

**Comment by gleitz** [comment]
Thanks for this! I'll let people use the snap file from this issue, rather than adding it to the codebase.
