### ISSUE TITLE
howdoi 不能用报的是不能连接网络，可以我是可以连接上google的。

### ISSUE THREAD

**Issue by forgeter** [gleitz/howdoi#159]
![image](https://cloud.githubusercontent.com/assets/12134040/24086989/d804e8e6-0d53-11e7-9d9f-d29c00ded66f.png)
python3.61,是不是我python版本太高了？？

**Comment by forgeter** [comment]
"C:\Program Files\python\Lib\site-packages\howdoi"目录下的 python.py '文件里 http: //www. google.com/search?q=site:{0}%20{1}'我不能连接也不能ping通。但是我能连上 "http: //www.google.com.hk/search?q=site:{0}%20{1}"，我改了这个连接就好了。
![87bo uu1t23 wom4y5ug0b](https://cloud.githubusercontent.com/assets/12134040/24087554/6a478428-0d5b-11e7-9a34-1afef49c49aa.png)

**Comment by ruanima** [comment]
需要设置代理
windows
```
set http_proxy=http://proxy.myproxy.com
set https_proxy=https://proxy.myproxy.com
```
其他参考http://stackoverflow.com/questions/11726881/how-to-set-an-http-proxy-in-python-2-7

**Comment by gleitz** [comment]
The windows version is quite outdated. Please let me know if setting the proxy as @ruanima mentioned worked for you.

**Comment by gleitz** [comment]
The windows version is not supported as it is terribly outdated

**Comment by wendingp** [comment]
I am using Shadowsocks on Mac OS, how do I set proxy?
