### ISSUE TITLE
standalone executable not working

### ISSUE THREAD

**Issue by mbkupfer** [gleitz/howdoi#161]
Closes immediately upon running. Tried debugging and this is the message I got:
```

C:\Users\foo>C:\Users\foo\Desktop\howdoi.exe
Sorry, couldn't find any help with that topic

```

**Comment by gleitz** [comment]
Sorry, the Windows version is quite old and not supported. If you would like to make a new exe for windows based off the latest howdoi version, I would accept a pull request.

**Comment by mbkupfer** [comment]
Pyinstaller is compatible up until py3.5 so I don't see this being any more
work than just running pyinstaller. If there is a caveat, please do share
and I wouldn't mind taking a stab at it.

**Comment by gleitz** [comment]
Yes I think creating an installer would be pretty straightforward. A community member submitted the last exe/intaller
