### ISSUE TITLE
Proposal: Open browser if query is bad

### ISSUE THREAD

**Issue by MathiasRenner** [gleitz/howdoi#170]
In case I am not happy with the results, I do:

- Copy the query string (`howdoi *QUERY*`)
- Open browser
- Paste Query
- Press ENTER
- Open the first 5 tabs to do a more thorough research

What about automating these steps with a `howdobrowser` ?

**Comment by Omar-Elrefaei** [comment]
Same

**Comment by gleitz** [comment]
You can do this on the command line as follows:

`howdoi --num-answers 3 --link parse html with regex | grep -v '^---' | xargs open`

This fetches the link of the top 3 results, removes the lines that say `--- Answer # ---`, and opens each of the results in the browser.

**Comment by Omar-Elrefaei** [comment]
Implemented this at #173

**Comment by gleitz** [comment]
If you're on linux you might want to use `xdg-open` or `gnome-open`.

I'm reluctant to add additional dependencies to the codebase when unix pipes will do the same job and are more customizable.

**Comment by MathiasRenner** [comment]
I like @Omar-Elrefaei 's implementation (https://github.com/gleitz/howdoi/pull/173) in general because of better UX.  It's just an `-b` and it opens the tabs in the browser.

Thus I would prefer to see the PR getting towards upstream.

**Comment by MathiasRenner** [comment]
@Omar-Elrefaei:
> xargs open gives me Couldn't get a file descriptor referring to the console [...]

Just use `firefox` instead of `open`.
Also, how do I put your code into my machine? I cannot find the local Python script path with at `python -m site --user-site`.

**Comment by Omar-Elrefaei** [comment]
from the README `pip install git+https://github.com/Omar-Elrefaei/howdoi.git#egg=howdoi`, Just changed the user to get the fork.
Or you can clone/download the repo localy and run `python setup.py install`

Hope that helps
