### ISSUE TITLE
To be able to set howdoi to search multiple sites

### ISSUE THREAD

**Issue by Omar-Elrefaei** [gleitz/howdoi#172]
Introduce the ability to easily set `$HOWDOI_URL` to search multiple sites by default, 
we can already set `$HOWDOI_URL` to something like `askubuntu.com OR site:serverfault.com` 
but it is not user-friendly and unintuitive,
I would rather it be `askubuntu.com:serverfault.com`

 --------------------------------------------------------------------
And to introduce user specified tags, for specific sites,

Example: after setting `$HOWDOI_URL` to both `askubuntu` and `stackoverflow`, and search for 
`howdoi install java` ->  it gives me instructions for Windows 7

So I think if it will be great to have an option to set some kind of tags,
Example: so the user would like to tag `askubuntu` with `+u` or `-t u` (-t for tag) so,
`howdoi +u install java` -> just give me Ubuntu/Linux related answers

**Comment by gleitz** [comment]
You can accomplish this using your `.profile` by making aliases that search each site. For example:

`function howdoi-serverfault { HOWDOI_URL=serverfault.com howdoi $@; }`

**Comment by Omar-Elrefaei** [comment]
Yeah, I think so. Sorry for the inconveniences

**Comment by gleitz** [comment]
No problem! Thanks for posting
