### ISSUE TITLE
1.11.1 not supported by bing

### ISSUE THREAD

**Issue by jian-en** [gleitz/howdoi#182]
I think these is a sync problem. The source code has already supported the env for HOWDOI_SEARCH_ENGINE, but when do:

pip install howdoi

The downloaded version has no support for HOWDOI_SEARCH_ENGINE.

**Comment by gleitz** [comment]
Haven't yet done a pip release with the new version. Will deploy that this week.

**Comment by gleitz** [comment]
Deployed in fff7a4e1050dcfc046efa9a47f089d45bf94c4b3
