### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by ammar-wizsoft** [gleitz/howdoi#183]
When i try to install on my mac with following command;
` brew install https://raw.github.com/gleitz/howdoi/master/howdoi.rb
`
It always gives 
`Error: SHA256 mismatch
`
I tried by removing ~/Homebrew/howdoi-1.1.11.tar.gz file also but didn't worked.

**Comment by gleitz** [comment]
Just pushed the latest version. Give it a try now.

**Comment by ammar-wizsoft** [comment]
Yea worked thanks!! 👍
