### ISSUE TITLE
A GUI for How Do I

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [gleitz/howdoi#189]
![howdoi screenshot](https://user-images.githubusercontent.com/13696193/36702327-a541b47c-1b24-11e8-9cc2-d22634ad6429.jpg)
I would like to show you guys an interesting use of HowDoI.  I wrote a GUI for windows that I use for all my projects.  Being a windows user, I like, well, windows.

The demo program included with my GUI can be found here:
https://github.com/MikeTheWatchGuy/gooeyGUI

The interface resembles a 'Chat' window.  Type your question in the area at the bottom and the response is shown in a scrolled window above.  I leave it running while I'm coding.  If I have a question it's one mouse click or hotkey press away.

Not sure of protocol for communicating stuff like this.

**Comment by gleitz** [comment]
That's cool! Is it written in a way that would work on OSX or Linux? I'm sure some users might be interested.

**Comment by MikeTheWatchGuy** [comment]
While I've not tried on any other OS's, it should all work pretty well.
My GUI code should work as it uses tkinter and no packages need be installed.

Maybe you can take a look and see how portable, or not, it may be.

I know I've got code in my GUI that force Python 3.X however.  I'm not 2.X compliant but I'm OK with that :-)

Here is ALL of the code for the HowDoI GUI version above.
```
import gooeyGUI as gg
import subprocess
import sys
HOW_DO_I_COMMAND = 'python C:\\Python\\PycharmProjects\\GitHub\\howdoi\\howdoi\\howdoi.py'
DEFAULT_ICON = 'E:\\TheRealMyDocs\\Icons\\QuestionMark.ico'

def HowDoI():
    '''
    Make and show a window (gooeyGUI form) that takes user input and sends to the HowDoI web oracle
    Excellent example of 2 new GUI concepts
        1. Output Element that will show text in a scrolled window
        2. Non-Window-Closing Buttons - These buttons will cause the form to return with the form's values, but doesn't close the form
    :return: never returns
    '''
    # -------  Make a new FlexForm  ------- #
    form=  gg.FlexForm('How Do I ??', AutoSizeText=True, DefaultElementSize=(30, 2), Icon=DEFAULT_ICON)
    form.AddRow(gg.Text('Ask and your answer will appear here....', Size=[40,1]))
    form.AddRow(gg.Output(Size=(90, 20)))
    form.AddRow(gg.Multiline(Size=(90, 5), EnterSubmits=True),
                gg.ReadFormButton('SEND', ButtonColor=(gg.YELLOWS[0], gg.BLUES[0])),
                gg.SimpleButton('EXIT', ButtonColor=(gg.YELLOWS[0], gg.GREENS[0])))

    # ---===--- Loop taking in user input and using it to query HowDoI web oracle --- #
    while True:
        (button, value) = form.Read()
        if button == 'SEND':
            command = value[0][:-1]
            QueryHowDoI(command)
        else:
            print(button, 'pressed')
            break

    print('Exiting the app now')
    exit(69)

def QueryHowDoI(Query):
    '''
    Kicks off a subprocess to send the 'Query' to HowDoI
    Prints the result, which in this program will route to a gooeyGUI window
    :param Query: text english question to ask the HowDoI web engine
    :return: nothing
    '''
    howdoi_command = HOW_DO_I_COMMAND
    t = subprocess.Popen(howdoi_command + ' '+ Query, stdout=subprocess.PIPE)
    (output, err) = t.communicate()
    print('You asked: '+Query + 'The HowDoI Oracle says:\n')
    print(output.decode("utf-8") )
    exit_code = t.wait()

if __name__ == '__main__':
    HowDoI()
```

**Comment by gleitz** [comment]
Thanks for the info. Going to close this issue for now but I hope people find your code useful.

**Comment by MikeTheWatchGuy** [comment]
I'm wondering if anyone has done a native windows application based on HowDoI.  I'm thinking of writing one like I did in Python, but instead do it in .NET.
