### ISSUE TITLE
A little confusion for the search engine

### ISSUE THREAD

**Issue by WindSoilder** [gleitz/howdoi#191]
Hi,
I have found that sometimes I run howdoi failed when I run it too frequently.  It may caused by the *Google* or *Bing* don't like spider, and it treated *howdoi* as a spider.  Then the search engine will lead us to capture page..

I wonder are there any ways to make us get rid of this? or we have to runs the program not too frequently..

**Comment by gleitz** [comment]
If you get rate limited you can look into using a proxy.
