### ISSUE TITLE
It doesnt work :(

### ISSUE THREAD

**Issue by Proliner** [gleitz/howdoi#198]
![screen shot 2018-04-24 at 21 52 19](https://user-images.githubusercontent.com/7000976/39210711-cc6f2a86-4809-11e8-8af1-9cee58b15e36.png)

**Comment by gleitz** [comment]
How did you install howdoi? What's the output of `howdoi -v`?

**Comment by gleitz** [comment]
Looks like this was fixed in https://github.com/gleitz/howdoi/issues/192
