### ISSUE TITLE
Difficulty with Windows install

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [gleitz/howdoi#201]
I don't understand what I'm doing wrong, but seems like something.

I have a running version of HowDoI installed on my system that I use with my PySimpleGUI interface. I posted about it already.  I see this interface when I want to use HowDoI.  It looks like this:
![snap0108](https://user-images.githubusercontent.com/13696193/42914288-95f5d08a-8ac7-11e8-8fc2-a1f182bd6176.jpg)

I querery howdoi by running a command line and collecting the output. I am running version 12 from a downloaded Github.  I am able to execute this command:
`python howdoi.py my_question`

I tried using pip and downloading from Github.  Both aren't working with the current version.

When I try to run howdoi.py from the github distribution, I get this error
```
A:\TEMP\HowDoI\12\howdoi>python howdoi.py test
Traceback (most recent call last):
  File "howdoi.py", line 19, in <module>
    from . import __version__
ImportError: cannot import name '__version__'
```

I want to get this solved so that I can include this program in my list of sample applications.  My front-end with your backend have been a lethal combination for me and my productivity.  Wanting to share this revelation with the world!   It also happens to be a great  use case to demonstrate.

**Comment by gleitz** [comment]
Check the README, you want to use :

python -m howdoi.howdoi QUERY

**Comment by MikeTheWatchGuy** [comment]
oh.. wow!!
This made it SO much easier!  I don't have hard coded paths anymore and I can run the latest version!

Thank you so very much for the fast response. My code looks better this way for sure.
