### ISSUE TITLE
I just released my GUI front end to HowDoI on PyPI....

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [gleitz/howdoi#211]
Hi there!

I'm such a huge fan of this project that I created a PyPI release of my GUI version.

It's called pysimplegui-howdoi

I'm probably using pip in a way not meant to be used but after installing it you can run the program by typing:
python -m pysimplegui-howdoi.pysimplegui.howdoi

![howdoi gui](https://user-images.githubusercontent.com/13696193/46993958-25c94800-d0e0-11e8-97f8-466664f1ced9.jpg)

I was wondering if I could get listed on your Wiki.  Maybe I could write a little section that other people that have integrated with HowDoI could also use?

I've not no motive other than wanting people to experience this tool the way I am.  It's incredible to hook up a hotkey with this GUI.  If I have a programming question, I hit the hotkey, type in the question, and I get back a result I can copy and paste into my code. 

As I previously wrote to you, it has changed the way I program.  

I think some people will not like it, especially if they're more junior and don't know how to filter out a great answer from a bad one.  It takes a seasoned programmer to really understand what's coming back.

Thank you for this effort!

**Comment by gleitz** [comment]
Looks cool! Go ahead and submit a PR with a link to the project

**Comment by MikeTheWatchGuy** [comment]
Very generous of you!  Thank you.  I edited the Wiki page.  I'm not sure how may people read these things, but for those that do, they'll learn about the GUI.

**Comment by gleitz** [comment]
You could also open a PR for the howdoi README. I think that gets more
views.

**Comment by MikeTheWatchGuy** [comment]
Done!  Feel free to reject with changes required.  I don't want to do anything that messes up your homepage!

I do think this GUI provides a nice, easy to use access to howdoi.

There seems to be a special kind of person that is an avid howdoi user.  I think you have to be quite skilled to use it and there are sometimes answers that don't fit.  However for other times, it's an incredible tool.  

Here's an example from this morning.  I needed to find the tkinter call that will make a window non-resizable.

![snag-0101](https://user-images.githubusercontent.com/13696193/47033063-e6334800-d141-11e8-8122-89502a3ae9f0.jpg)


As is OFTEN the case with my queries, the right answer is the first one and I'm able to copy and paste the solution and continue with my coding.

**Comment by MikeTheWatchGuy** [comment]
Wow!  I posted on my GitHub, here and on Reddit that I made this GUI.  The number of Pip installs of the GUI that day was CRAZY!  PePy recorded  2,119 installs that day!  You've got a great following!

**Comment by gleitz** [comment]
very nice!!

**Comment by MikeTheWatchGuy** [comment]
It's all YOU man... you've built an amazing thing.  I wish more people understood how to use it.  It's not always a literal use.  It gives me just enough of a hint to understand what to do.  It's not a copy and paste many times.  I think that throws off the  younger people in particular.  "It's not the right answer".  

What did you think of the readme edits?  I would be happy to make it look however you want.  I used an online rst editor as I've never edited one of these before.  All of mine are .md files.

**Comment by MikeTheWatchGuy** [comment]
Thanks for your support.

**Comment by gleitz** [comment]
Sure thing. Thanks for creating this
