### ISSUE TITLE
syntaxError

### ISSUE THREAD

**Issue by craigboman** [gleitz/howdoi#219]
No issues installing. During python cli, when I try howdoi followed by anything, I only get a syntax error. Using Python v3.6.6.

>>> howdoi write
  File "<stdin>", line 1
    howdoi write
               ^
SyntaxError: invalid syntax

**Comment by craftyguy** [comment]
I don't think this is meant to be imported as a module and used, there are no 'public' methods. Just:

```
$ ./howdoi write 
read()

```
