### ISSUE TITLE
Suddenly stopped returning any answers

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [gleitz/howdoi#220]
I'll admit that I'm addicted to this tool, especially with the GUI front-end.  I use it 10 times a day, at least.  When I'm working on a new SDK and don't know the API calls, I can simply ask.  

Now anything I ask gives the same response.
> Sorry, couldn't find any help with that topic

I tried upgrading to 1.1.14 (from 1.1.13) but didn't help.

Is there a log I can turn on?

I'm invoking by entering:
`python -m howdoi.howdoi test`

I've made no changes that I can recall that modified python or packages.  It was working this morning.

**Comment by gleitz** [comment]
Google will rate limit you if it sees too many requests from the command line. You'll see this if you inspect the HTML response that is returned. 
If you wait a few hours it will go away. In the meantime use the variable to switch to Bing

**Comment by MikeTheWatchGuy** [comment]
can I do that from the command line?  I don't see an option.  What's the variable I would modify?

**Comment by gleitz** [comment]
Yep 
`export HOWDOI_SEARCH_ENGINE="bing"`

**Comment by MikeTheWatchGuy** [comment]
ah, I went in and modified the code directly.

I'll have to look up export.  Haven't used it before.

**Comment by MikeTheWatchGuy** [comment]
Where do I put this export statement?

**Comment by gleitz** [comment]
You put it into the command line before you run the program. See
https://stackoverflow.com/a/7328289

I think in your case you will probably just want to change the source code
itself to point to bing, because it sounds like you're using it within a
GUI.
