### ISSUE TITLE
Implement simpler caching scheme

### ISSUE THREAD

**Issue by Almenon** [gleitz/howdoi#224]
As I found out in #213 requests_cache has some severe performance issues. By switching to a simpler caching scheme we should be able to massively speed up start time while still offering caching for the last X requests, X being however many we can store untill running into perf problems on a HDD. 

The caching scheme could be as simple as just appending the request/answer as csv. Or maybe as JSON? Or storing requests in one file and answers in another?  Or using [diskcache](https://github.com/grantjenks/python-diskcache)?  And I'd have to get rid of oldest entries to prevent cache from growing too large too.

Anyways, I'm planning on implementing this, Just wanted to give you a heads up before I start work.

**Comment by gleitz** [comment]
Sounds wild!

**Comment by paulie-g** [comment]
Why not just use an array of N (argv, output) tuples in a pickle? Load it at start and concurrently with the first network request. If it's a hit, output and cancel network request; if it's a miss, after producing output evict one entry from the array by LRU and pickle onto disk. Speed-up for hits, virtually no visible penalties for the vastly more common miss case.

**Comment by paulie-g** [comment]
So the initial commit is in (to fastercache branch in my fork). See: https://github.com/paulie-g/howdoi/commit/24bfdcad98c605e0d172ae6b598bdd49ed2f9d65

requests_cache is removed completely. Instead, we're using cachelib.FileSystemCache (cachelib is the caching stuff from werkzeug/pallets/flask/etc broken out into a separate package). It's not perfect, but it's the best I could find without rolling my own. Basic principle is you give it a directory, key = filename and contents=pickled(date-modified,value). We set it to hold x items (currently 64 iirc) and it automatically purges when it needs to (suboptimally). I'd like to improve it in a number of ways, but it's not clear the loss of maintainability is worth it.

Results are clear, I get ~70ms (down from ~220 to ~150) in the hit case and even a bit more in the miss case. It's only 10-15% of total runtime in the common, miss case on my box, but it's the last of the big wins and very much worth it imo.

With this initial commit, we're caching output directly and keying it on all arguments. This is great when you're just re-running a search. It leaves the case where the user now wishes to colorize (or not), display more answers etc on a subsequent run uncached. I see no use in paying for caching in the common case to serve those cases, but if you do, I'll add a second-level cache to handle them.

I think the best way forward would be for @gleitz to create a 'fastercache' branch on this repo. This way I can submit PRs to it without fear of breaking master/head. I've got a few minor tweaks (like using appdirs, already in commit) and some others (still to come) as well. Once they're all in and passing Travis (I only test on 3-latest an 2-latest), we can merge.

**Comment by gleitz** [comment]
Sounds good to me. https://github.com/gleitz/howdoi/tree/fastercache

**Comment by paulie-g** [comment]
OK, I think I'm done with the caching for now. We have a three level cache - output, links (from SE), and full html. We also have detection for Google blocks with reCaptcha, and a few minor performance tweaks.

I have a few other things in mind, one of them big. Provided this meets with @gleitz 's approval (cache hit case is down to ~155ms on my box, and everything appears to work), I'd like this merged into master so I can rebase and start a few more branches. Doing them off master could result in too many conflicts at this point. I propose we also create a 'dev' branch here so I can submit PRs to it as I find time.

**Comment by paulie-g** [comment]
I think we can aim to close this in a week or so if no bugs in the new implementation emerge.

**Comment by gleitz** [comment]
Sounds good to me. Let's work off the `fastercache` branch now that the other PR was merged.

**Comment by paulie-g** [comment]
Make a `dev` branch instead maybe? It's probably a good idea to have a second branch for unstable dev anyway for a project of this popularity. Purely cosmetic considerations against re-purposing a feature branch as a catch-all for dev commits.

**Comment by gleitz** [comment]
https://github.com/gleitz/howdoi/tree/dev

currently cut off `fastercache`

**Comment by gleitz** [comment]
@paulie-g are there any outstanding items here?

**Comment by Almenon** [comment]
Nothing on my end. I assume the new version (1.2.0) has the changes? I noticed some issues when installing the new version, but I'll raise a seperate issue for that.

**Comment by Almenon** [comment]
thanks for making the change @paulie-g

**Comment by gleitz** [comment]
Fixed in version 2.1.0
