### ISSUE TITLE
setuptools-installed howdoi is dog slow

### ISSUE THREAD

**Issue by paulie-g** [gleitz/howdoi#230]
As promised, I've done some digging. Part of the speed problem is setuptools. Doing a `python setup.py install` causes a pkg_resources import in the launch script. This costs over 200ms on my machine (with a pcie ssd + warm cache). This does *not* happen if you install with a wheel, so either via pip from pypi or `python setup.py bdist_wheel + pip install dist/something.whl`

This may not matter to _you_, me or people who use pip ahead of their distro's package manager, but for everyone else it's a problem since packagers are unlikely to bother with wheels (and the added requirements). The AUR package uses setuptools for example, and I'm sure so do others.

See:
* as is, importing pkg_resources naively (cache hit)
(paul@redacted)[~/dev/howdoi/howdoi]$ hyperfine  'howdoi bash history search'
Benchmark #1: howdoi bash history search
  Time (mean ± σ):     439.9 ms ±   4.0 ms    [User: 383.4 ms, System: 49.5 ms]
  Range (min … max):   435.8 ms … 448.9 ms    10 runs
 
* fast-entry_points magic (cache hit)
(paul@redacted)[~/dev/howdoi/howdoi]$ hyperfine  'howdoi bash history search'
Benchmark #1: howdoi bash history search
  Time (mean ± σ):     221.8 ms ±   3.7 ms    [User: 186.7 ms, System: 28.8 ms]
  Range (min … max):   217.4 ms … 229.3 ms    13 runs

* installed with pip + wheel (cache hit)
(paul@redacted)[~/dev/howdoi/howdoi]$ hyperfine 'howdoi bash history search'
Benchmark #1: howdoi bash history search
  Time (mean ± σ):     214.3 ms ±   4.5 ms    [User: 187.7 ms, System: 26.5 ms]
  Range (min … max):   208.0 ms … 223.5 ms    14 runs

I would argue that given we can't control the packagers, it's best to fix it in howdoi itself.

**Comment by gleitz** [comment]
Thanks for digging. Does your PR address the issue and we can close? Or is there more you would like to do?

**Comment by paulie-g** [comment]
Yes, my PR works around the issue. Wheels are still faster by ~2ms, but it's close. We might want to stick a nota bene in the readme for packagers to use wheels if they can (I can submit a PR for that too if you like).

I do intend to dig further (replacement caching, which is half-way done), but it'll be a separate issue and separate PR.

**Comment by gleitz** [comment]
Closing this since we merged the PR. Re-open if you have other thoughts

**Comment by gleitz** [comment]
@paulie-g wanted to let you know this was released as howdoi v1.2.0. Thanks again for all your help.

**Comment by paulie-g** [comment]
@gleitz Most welcome. Great that it's all out and available for use by the wider userbase now.
