### ISSUE TITLE
Unit tests sometimes fail when using bing

### ISSUE THREAD

**Issue by paulie-g** [gleitz/howdoi#234]
.FF...............
======================================================================
FAIL: test_answer_links_using_all_option (__main__.HowdoiTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_howdoi.py", line 76, in test_answer_links_using_all_option
    self.assertNotEqual(re.match('.*http.?://.*questions/\d.*', response, re.DOTALL), None)
AssertionError: None == None

======================================================================
FAIL: test_answer_links_using_l_option (__main__.HowdoiTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_howdoi.py", line 71, in test_answer_links_using_l_option
    self.assertNotEqual(re.match('http.?://.*questions/\d.*', response, re.DOTALL), None)
AssertionError: None == None

----------------------------------------------------------------------
Ran 18 tests in 26.040s

**Comment by gleitz** [comment]
Interesting – I wonder if it hits a bing rate limit. I tried running with `HOWDOI_SEARCH_ENGINE='bing' nosetests`

**Comment by paulie-g** [comment]
The only reason I was running them with bing is I'm getting sin-binned by google all the time now, it seems much easier than previously. Maybe I've sped the thing up so much it's hitting ratelimits it never could before ;)

**Comment by gleitz** [comment]
It's a separate question, but I do wonder if goog does the rate limiting per IP, or if there is something we can twiddle with the session to avoid the all-seeing 👁 👁

**Comment by paulie-g** [comment]
Yes, it's per-ip, but there are other factors as well. We're not loading google.com first, we're not supplying the natural header/cookie profile with our request, we don't have any of the usual utm source query params, we're not loading any of the other resources on the page, ad infinitum.

Yes, there are things we can do, but google wages a constant battle with scrapers and they've been winning consistently (the only way scrapers work is by using a large and expensive pool of ips). This is why seo rank trackers are so expensive. Thankfully, our *users* won't be running into this - it's just hitting us in the face on unittests. Not worth jumping through hoops for that, imo, and if it were the easier solution would be to mock google's response.

**Comment by gleitz** [comment]
@paulie-g do you have any thoughts on how to fix this other than stubbing the response from google/bing? Wondering if we should close this issue or not.

**Comment by paulie-g** [comment]
Yeah, I say we close it because it has no impact on users.

Ideally, any software that depends on querying a remote resource should have mocking of said resource built into its unit test suite. Most of the unit tests can then run against the mocked resource that always returns what is expected, while a small number can optionally run against the real thing to confirm that basic assumptions about what it returns still hold. This would obviously solve the blocking issue and is the classically "correct" way to do this.

A useful kludge would be to simply add a wait to each test, thereby spreading them over a longer time period. We have ~16 unit tests and they really can't get us blocked unless we run them at such a breakneck speed one after another that they trip every statistical outlier alarm at google/bing, which is what we're currently doing. Even something like a 5 to 15 sec randomized delay would probably work. This would be trivial to add, but I'm not the right person to do it because all of my ips are on the naughty list at google - someone with a cleaner history should see if it's sufficient.

Stepping back, this runs into an absurd complexity argument - howdoi is very useful, and very popular, but it really isn't all that complex. Having a unit test suite that starts approaching the complexity of the thing it is testing is absurd. This is just my view since I come from a systems programming background where we don't unit test anywhere near as much as people do in userspace. Unit testing cultists have a drastically different view obviously. I would argue that the current testing suite is more than fit for purpose.

**Comment by gleitz** [comment]
Yes I like the idea of putting in the sleeps. The point of the test was a bit more in the earlier days when I was trying to see if `-n 3` actually returned the correct thing. Now, it's more of a check to see if the thing functions at all after a new commit.

**Comment by gleitz** [comment]
https://github.com/gleitz/howdoi/commit/8d07eb1c6727134335eb91b7f7aabb17472eca90
