### ISSUE TITLE
-n >1 often returns duplicate answers

### ISSUE THREAD

**Issue by paulie-g** [gleitz/howdoi#236]
When requesting multiple answers, there are often duplicates stemming from google's cache links. Unless this is intentional, we might want to tighten up the match in the is_question filter.

**Comment by gleitz** [comment]
Good catch 👌 
I saw that too in the other thread

**Comment by gleitz** [comment]
I can't tell if they're "better answers" or not. Part of me wants to keep the search results pure, but the ultimate goal is getting an answer you're happy with

**Comment by paulie-g** [comment]
Well, they're not coming from search results per se. We're just parsing out the link to a google-cached version of the page from one given result because of a too loose parsing rule. It's what you get if you click on 'Cached' below the main result link on the right. No added value. In theory, the cached version could be older and differ, but I've never seen this in practice.

**Comment by lrichert** [comment]
Instead of blacklisting unwanted elements, couldn't we just match the main result?
`html('.rc > .r > a:first')`
