### ISSUE TITLE
An function to use howdoi from inside python

### ISSUE THREAD

**Issue by MarcSkovMadsen** [gleitz/howdoi#238]
Thank you for providing such a useful tool. I have started using it from the cli all the time. 

Now I would like to be able to using from within python, ipython and notebooks because it's not effective to switch from ipython to a normal terminal to find out howdoi... and then back again.

I cannot find any documentation on it. I also looked at the code and it does not seem supported.

The user story is

'As a data scientist i can use howdoi in from python, ipython and notebooks in order to work more efficiently by writing

from howdoi  import howdoi
howdoi("create pairplot using seaborn")'

**Comment by gleitz** [comment]
Thanks for using howdoi. You can use it from within other applications like [this](https://github.com/gleitz/howdoi/issues/227).
