### ISSUE TITLE
KeyError: 'search_engine' on start up

### ISSUE THREAD

**Issue by hdboer** [gleitz/howdoi#239]
When starting with following command line:
> howdoi -n 3 python dictionary comprehension
this exception is thrown:
Traceback (most recent call last):
  File "C:\Users\hansd\Envs\hdb_py3\Scripts\howdoi-script.py", line 12, in <module>
    sys.exit(command_line_runner())
  File "d:\hans\ccm_wa\mypython\howdoi-master\howdoi\howdoi.py", line 421, in command_line_runner
    if args['search_engine'] != 'google':
KeyError: 'search_engine'

This is caused by the used key 'search_engine' while the command line parser is defined with the 'engine' option. Easily solve by adding 'default="search_engine"' to the engine option in the set up of get_parser().

**Comment by gleitz** [comment]
Thanks for reporting. Would you minding submitting a PR with that fix?

**Comment by hdboer** [comment]
It is yours

**Comment by gleitz** [comment]
Fixed in #240
