### ISSUE TITLE
It doesn't work!

### ISSUE THREAD

**Issue by iamsoorena** [gleitz/howdoi#241]
what I did?!
```
pip3 install howdoi
howdoi format date bash
```
what it prints:
```
Sorry, couldn't find any help with that topic
```

**Comment by gleitz** [comment]
Thanks for using howdoi. Are you in Tehran? Is it possible that Google is blocked there?

You can try using Bing with 

```
HOWDOI_SEARCH_ENGINE=bing howdoi format date bash
```

**Comment by iamsoorena** [comment]
I'm in Tehran, but I'm running those commands on an almost untouched server in Tokyo.
just a simple Ubuntu 16.04 instance.
you can try it our yourself.
(btw Tehran's error is different due to censorship 😄)

**Comment by iamsoorena** [comment]
Ok, confirmed. Bing is working in Tokyo.
I think something is wrong with Google in general. (the way the code is implemented)

**Comment by gleitz** [comment]
Feel free to take a look at the code and submit a PR if necessary. From past user reports, Google is occasionally blocked in certain locations and setups.

**Comment by iamsoorena** [comment]
this is the error in Dev mode:
```
[ERROR] Unable to find an answer because the search engine temporarily blocked the request. Please wait a few minutes or select a different search engine.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/howdoi/howdoi/howdoi.py", line 436, in <module>
    command_line_runner()
  File "/root/howdoi/howdoi/howdoi.py", line 425, in command_line_runner
    utf8_result = howdoi(args).encode('utf-8', 'ignore')
  File "/root/howdoi/howdoi/howdoi.py", line 367, in howdoi
    res = _get_instructions(args)
  File "/root/howdoi/howdoi/howdoi.py", line 318, in _get_instructions
    question_links = _get_links_with_cache(args['query'])
  File "/root/howdoi/howdoi/howdoi.py", line 307, in _get_links_with_cache
    links = _get_links(query)
  File "/root/howdoi/howdoi/howdoi.py", line 205, in _get_links
    raise BlockError("Temporary block by search engine")
__main__.BlockError: Temporary block by search engine

```

**Comment by iamsoorena** [comment]
I think you are right, although it's odd that I can easily `ping google.com` @gleitz

**Comment by gleitz** [comment]
Going to close this for now - please use Bing. Google has lots of checks on their search engine and sometimes it doesn't work depending on your setup.

You can use the following:

```alias howdoi_bing='HOWDOI_SEARCH_ENGINE="bing" howdoi'```

**Comment by paulie-g** [comment]
@iamsoorena Google almost never blocks all traffic at the network level from a particular IP - you would have to do something special to earn yourself that sort of block. The vast majority of the time they'll just return an error page stating that you've been blocked and possibly offer a chance to complete a captcha to prove you're not making automated requests. Therefore, being able to ping google.com (which is either an ICMP or UDP packet with a particular value in the TTL field) is completely useless in ascertaining whether google has blocked you at the application level. @gleitz is correct in that you should temporarily use bing until the google block is lifted.

**Comment by paulie-g** [comment]
@gleitz The thing I'm curious about is why being blocked doesn't result in the [ERROR] being displayed on stdout. if we're blocked, and detecting that we're blocked correctly, we shouldn't be producing a 'no results found', no?

**Comment by gleitz** [comment]
Yes, that would be a good addition.
