### ISSUE TITLE
Cache with several HOWDOI_URL

### ISSUE THREAD

**Issue by webmastak** [gleitz/howdoi#244]
I have such a construction in my .zshrc

```
hdi() { 
	export HOWDOI_DISABLE_CACHE=true
	howdoi -c -n 5 $@ 
}

alias hq='export HOWDOI_URL="qaru.site" && hdi $1'
alias h='unset HOWDOI_URL && hdi $1'
```

This only works when you turn off the cache - `export HOWDOI_DISABLE_CACHE=true`

If the cache does not turn off then for example:
if we search with **h** alias and then **hq**
then the result will be cached with **h** alias, even if you search by **hq** alias.

Is there a workaround so as not to disable the cache?

**Comment by paulie-g** [comment]
A quick workaround is to pass different command line arguments as this will produce different keys for the output cache. You can remove -c, change the -n parameter and so on. 

@gleitz: For a permanent fix, I think all the env parameters should have long cmd line argument equivalents.

**Comment by webmastak** [comment]
> You can remove -c, change the -n parameter and so on.

Not Works!

**Comment by paulie-g** [comment]
There are three caches. One is the output cache, which is keyed on command line args. This is what my suggestion was about. There is also a cache for the SERPs, keyed on the query, which currently does not include the site. If you've tried varying the arguments and are still having issues, this is what you're running into. There is a page cache also, but that's not a problem.

Fundamentally, there are two issues here: parameters passed via env should have cmnd line equivalents and the site should be included in the SERP cache key.

You're very welcome to submit a PR fixing one or more of those issues. PRs get feedback and merges quickly. Alternatively, as a workaround you can adopt a convention that you add something like '_ ' or 'the' to the beginning or end of every query to the secondary site 'date format in bash _'. Both google and bing will ignore it, but it will be enough to vary the cache key in a way that will work for you.

**Comment by webmastak** [comment]
Honestly i'm not strong in python. And the time that saves the cache is about 4 seconds, I can do without it.

**Comment by paulie-g** [comment]
Replacing $1 with $1+' _' in your alias isn't that difficult.
This will get fixed eventually when we rework the config/param system.

**Comment by webmastak** [comment]
Works, many thanks. )

**Comment by paulie-g** [comment]
Thanks for reporting the issue. We'll ping you when it's fixed if you stay subscribed :)

**Comment by gleitz** [comment]
Going to close this for now, but please re-open if you have a PR for review.
