### ISSUE TITLE
readme should be updated to reflect python3

### ISSUE THREAD

**Issue by njm2112** [gleitz/howdoi#262]
pip/python2.7 is deprecated as of 1 January 2020, so install instructions should be updated to reflect use of pip3/python3.

thanks for continued support of this -- find uses for this all the time!

**Comment by gleitz** [comment]
Thanks for the note. What would you recommend? I think, with 2.7 or 3.x, a simple `pip install howdoi` should work. Folks who are using pip3 should already have that symlinked, and folks on older machines with just pip will still be able to install it.

**Comment by gleitz** [comment]
I'd be happy to accept a PR, but closing this for now as I assume there are still some people using 2.7 who could benefit.
