### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by gmelodie** [gleitz/howdoi#278]
- [x] Setup documentation pages (github pages)
- [x] Deep link from README into mkdocs (http://gleitz.github.io/howdoi)
- [ ] Plugin documentation (#275)
- [ ] JSON schema (#274)
- [ ] Testing (#277)
- [ ] Improvements

**Comment by gmelodie** [comment]
@gleitz Maybe we could use [asciinema](https://asciinema.org/) to record the terminal and setup interesting example gifs in the README

**Comment by chrisngyn** [comment]
I think a .gif would be a nice idea. I've done that before in my prior repositories, if Benjamin approves I'd be glad to record myself using howdoi.

Will be updating the README with the new `-j` flag as well as how to prettify it if need be using `json.tool`

**Comment by IamCathal** [comment]
Typer uses [termynal](https://github.com/ines/termynal/) and it really added to the overall finish of their docs. Not only can you show off using some flags and options using it but it also shows the output in an interactive manor which is great.

I've never used it before but it can't be that hard

**Comment by joeyouss** [comment]
Hey @gleitz I am interested in working on this. Can you assign the issue to me ?

**Comment by ShezaMunir** [comment]
Hello! I'd like to work on the GitHub documentation page design for this
