### ISSUE TITLE
Howdoi logo

### ISSUE THREAD

**Issue by gmelodie** [gleitz/howdoi#291]
I think it'd be cool to have a logo for howdoi. We could showcase it on the `README` and on the future `docs`

**Comment by gleitz** [comment]
Already in the works. Should have something in a week or so

**Comment by gleitz** [comment]
First draft as we figure out colors:

![image](https://user-images.githubusercontent.com/395254/90423624-a73de880-e071-11ea-8406-1665941cbd86.png)

**Comment by diarreola** [comment]
@gleitz Can I use one of these for the vscode-ext?

**Comment by gleitz** [comment]
We're getting pretty close. I'm going to switch away from the green toward something a little more blue or purple. Will ping you when we have a final design.

**Comment by gleitz** [comment]
Here are some different sizes. @diarreola feel free to take the 128px for your vscode extension.

![HowDoIcolor32](https://user-images.githubusercontent.com/395254/90470751-1d256c80-e0d1-11ea-887e-161b5aa2b5c8.png)
![HowDoIcolor128](https://user-images.githubusercontent.com/395254/90470754-1dbe0300-e0d1-11ea-8908-eda5b01afdee.png)
![HowDoIcolor512](https://user-images.githubusercontent.com/395254/90470755-1e569980-e0d1-11ea-9b13-0dd676d2dad8.png)
![HowDoIcolor838](https://user-images.githubusercontent.com/395254/90470760-1f87c680-e0d1-11ea-8926-0ad380b764ff.png)

**Comment by gleitz** [comment]
Colors for reference: purple (#ab9df2), light blue (#78dce8), pink (#ff6188), and yellow (#ffd866)
