### ISSUE TITLE
Add multiple requirement files

### ISSUE THREAD

**Issue by gmelodie** [gleitz/howdoi#293]
For now we only use one `requirements.txt` file. As the project is growing (plugins, better linting and testing, new docs) I think we could split the requirements file into multiple files. Here's a structure I'm thinking about (stole from [this comment](https://stackoverflow.com/a/20720019/6032037)):

```
-- howdoi_root
|-- requirements
|   |-- common.txt
|   |-- dev.txt
|   |-- prod.txt
-- requirements.txt
```

**Comment by hmanalai** [comment]
I have created a PR for this issue that adds the requirements folder and the stated .txt files. As of now, common.txt contains all the requirements in requirements.txt.
