### ISSUE TITLE
`howdoi square root python` returns wrong answer?

### ISSUE THREAD

**Issue by chenrui333** [gleitz/howdoi#295]
## Current behavior

```
$ howdoi square root python
pow
```

## Expected behavior

```
$ howdoi square root python
sqrt=x**(1/2)
```

**Comment by gleitz** [comment]
Sometimes the first answer isn't exactly right, so try throwing a `-n3` (for 3 answers) or `-a` (for the entire answer). 

You can also try expanding the search query. 

`howdoi calculate square root python -a` gives a pretty good answer.

**Comment by chenrui333** [comment]
Good to know `-a` option, thanks!
