### ISSUE TITLE
Please tag your release revisions in git

### ISSUE THREAD

**Issue by risicle** [gleitz/howdoi#309]
Or even create proper github "releases".

It's extremely useful to be able to quickly look up the exact source of the release your working with in github, especially for people trying to package your tool.

**Comment by gleitz** [comment]
Good point. We now have our first tag, https://github.com/gleitz/howdoi/tree/v2.0.5

**Comment by gleitz** [comment]
BTW, what are you developing?

**Comment by risicle** [comment]
https://github.com/NixOS/nixpkgs/pull/96839

**Comment by gleitz** [comment]
That is pretty cool. I had pruned `page_cache` from the tarball but I can put it back if that will make your life easier.

**Comment by risicle** [comment]
I imagine there are good (size) reasons to leave it out, in these cases we usually just pull the archive from github instead, hence this request.

**Comment by gleitz** [comment]
Thanks. I appreciate you maintaining this and do let me know if there's anything else you need.
