### ISSUE TITLE
Query returns always 'Sorry, couldn't find any help with that topic'

### ISSUE THREAD

**Issue by a2x** [gleitz/howdoi#315]
```
howdoi print hello world in python
Sorry, couldn't find any help with that topic
```
Is this project alive?

**Comment by gleitz** [comment]
Thanks for the report. Seems something is up with Google. You can workaround it with:
```
howdoi print hello world in python -e duckduckgo
```

**Comment by gleitz** [comment]
Fixed in https://github.com/gleitz/howdoi/commit/9d35399a8e38117fce32fc0290f70f7685e5cc2d

**Comment by reuseman** [comment]
Just upgraded and I have the same problem even with duckduckgo

**Comment by gleitz** [comment]
```~ » howdoi print hello world in python
print("Hello, World!")
~ » howdoi print hello world in python -e bing
print("Hello, World!")
~ » howdoi -v
2.0.7
```

Seems to work for me. You might want to clear the cache with `howdoi -C`

**Comment by athoca** [comment]
I have the same problem now. I tested with 2.0.7 and 2.0.8, both google, bing and duckuckgo. Run with python 3.7.4
