### ISSUE TITLE
Not working using Python 3.6.9

### ISSUE THREAD

**Issue by tassosblackg** [gleitz/howdoi#317]
Hi, 
when I am trying to use it shows 

> Sorry, couldn't find any help with that topic 

no matter what I search for even when I am using the standard example for format date query, any suggestions?

I've tried to reinstall it a couple of times but nothing happened.

P.S. it was working but recently I got this error

**Comment by tassosblackg** [comment]
Now is working again, all of a sudden. Weird..

**Comment by gleitz** [comment]
I pushed a new version that fixed this issue

https://github.com/gleitz/howdoi/issues/315#issuecomment-702986184
