### ISSUE TITLE
howdoi get the json result using python ?

### ISSUE THREAD

**Issue by aahnik** [gleitz/howdoi#320]
```python
from howdoi import howdoi

query = "for loop python"
output = howdoi.howdoi(query)
```

this returns a string, but can I get a python object ( dictionary or list of dictionaries) or JSON ?

I have seen that the `_get_answers()` return the JSON, should I call that directly ? or is there a good way?

**Comment by WindSoilder** [comment]
> I have seen that the _get_answers() return the JSON, should I call that directly ? or is there a good way?

Normally, you shouldn't try to call a private function directly...Else when `_get_answers()` changed, your code is easily to break

**Comment by aahnik** [comment]
@WindSoilder exactly, thats why i asked the question. What is a good way of doing this ?

**Comment by aahnik** [comment]
I found a way. It was obvious, but I did not notice.

```python
from json import JSONDecoder
from howdoi import howdoi
jd = JSONDecoder()

query = 'python for loop'

answers = jd.decode(howdoi.howdoi(f'{query} -j'))

# type(answers) is list

for item in answers:
    print(type(item))
    print(item)
```

**Comment by gleitz** [comment]
Nice, I'll add that to the documentation.

```
    from howdoi import howdoi
    import json

    query = "for loop python"

    output_json = json.loads(howdoi.howdoi(f'{query} -j'))
```
