### ISSUE TITLE
Will it parse comments too?

### ISSUE THREAD

**Issue by SmartManoj** [gleitz/howdoi#324]
![image](https://user-images.githubusercontent.com/7231077/101977868-b5de8a00-3c76-11eb-9f41-aed830866bbf.png)

[Source link](https://stackoverflow.com/questions/15920496/difference-between-element-node-and-text-node)

**Comment by aahnik** [comment]
Please run this in command line once

**Comment by SmartManoj** [comment]
Does it take the snippet from [this comment](https://stackoverflow.com/questions/15920496/difference-between-element-node-and-text-node#comment22677265_15920567)?

**Comment by gleitz** [comment]
Nice find! I'm not sure if the CSS classes changed, but I submitted a fix in https://github.com/gleitz/howdoi/pull/325
