### ISSUE TITLE
Not working after update.

### ISSUE THREAD

**Issue by keithdadkins** [gleitz/howdoi#328]
`howdoi` only returns "Sorry, couldn't find any help with that topic" after latest update.

```bash
$> howdoi compare arrays in bash
Sorry, couldn't find any help with that topic
```

This worked last week.

```
$> brew info howdoi
howdoi: stable 2.0.9 (bottled)
Instant coding answers via the command-line
https://github.com/gleitz/howdoi
/usr/local/Cellar/howdoi/2.0.9 (1,664 files, 22.2MB) *
  Poured from bottle on 2021-01-14 at 11:53:30
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/howdoi.rb
License: MIT
==> Dependencies
Required: python@3.9 ✔
==> Analytics
install: 574 (30 days), 1,332 (90 days), 5,085 (365 days)
install-on-request: 574 (30 days), 1,332 (90 days), 5,067 (365 days)
build-error: 0 (30 days)
```

**Comment by gleitz** [comment]
I'm seeing that as well. Doesn't seem to work with any of the other engines (`-e bing` either). I wonder if StackOverflow changed their CSS.

**Comment by Kebroid** [comment]
Same for me!

**Comment by gleitz** [comment]
Actually, looks like bing is working. You can do a 
`howdoi -C` to clear the cache and then `howdoi {QUERY} -e bing` to use bing instead.

Will see what's up with Google...

**Comment by gleitz** [comment]
If others could check the source of their Google results and confirm I would appreciate it. I see this:

<img width="515" alt="Screen Shot 2021-01-15 at 11 52 34 AM" src="https://user-images.githubusercontent.com/395254/104772395-3a19a680-5728-11eb-8570-0e2475215fa1.png">

**Comment by gleitz** [comment]
(hopefully) fixed in https://github.com/gleitz/howdoi/commit/fd382ac54f26b48acadd63de3af1e06407a57c55

**Comment by gleitz** [comment]
`v2.0.10` released, give it a spin and let me know if it's working for you.

`pip install -U howdoi`

https://pypi.org/project/howdoi/2.0.10/

**Comment by keithdadkins** [comment]
Works for me as long as I initially cleared the cache after installing the pip version. Thanks for the quick response! Awesome tool I use daily 🥇 

```
brew uninstall howdoi
pip install -U howdoi
$> howdoi -C compare arrays in bash
Cache cleared successfully
Array1=( "key1" "key2" "key3" "key4" "key5" "key6" "key7" "key8" "key9" "key10" )
Array2=( "key1" "key2" "key3" "key4" "key5" "key6" )

Array3=()
for i in "${Array1[@]}"; do
    skip=
    for j in "${Array2[@]}"; do
        [[ $i == $j ]] && { skip=1; break; }
    done
    [[ -n $skip ]] || Array3+=("$i")
done
declare -p Array3
```

**Comment by gleitz** [comment]
Thanks for confirming. Happy hacking!
