### ISSUE TITLE
Full Python 3 support

### ISSUE THREAD

**Issue by gleitz** [gleitz/howdoi#329]

**Comment by gmelodie** [comment]
Here are a couple features we could implement (this is gonna be a good dive into specifics and best practices for python!):

- [ ] [f-strings](https://realpython.com/python-f-strings/)
- [ ] Type hinting (optional, might be too much work)
- [ ] Use [`pathlib`](https://realpython.com/python-pathlib/) for handling file paths when needed
- [ ] [Extended iterable unpacking](https://www.python.org/dev/peps/pep-3132/)
- [ ] [Assignment Expressions: The Walrus Operator](https://realpython.com/lessons/assignment-expressions/)
- [ ] [Named tuples](https://stackoverflow.com/questions/2970608/what-are-named-tuples-in-python)
- [ ] [`__repr__`](https://www.educative.io/edpresso/what-is-the-repr-method-in-python) and [`__iter__` and `__next__`](https://www.programiz.com/python-programming/iterator) in classes
- [ ] [Decorators](https://realpython.com/primer-on-python-decorators/)


**Obs**: some of those might not be needed (e.g. we wouldn't need f-strings if we didn't need strings).
**Credits**: ideas heavily inspired on [this medium post](https://medium.com/better-programming/9-python-3-features-you-might-not-use-yet-fade13932a3e) as well as some other sources.

**Comment by KimaruThagna** [comment]
@gmelodie Just to mention, the referenced medium [post](https://medium.com/better-programming/9-python-3-features-you-might-not-use-yet-fade13932a3e) is suspended. So maybe we need to update your comment.

**Comment by gleitz** [comment]
That's wild. Here's a screencap of what used to be in the article.

![screencapture-getpocket-read-3097150344-2021-02-24-14_08_50](https://user-images.githubusercontent.com/395254/109072473-eea0d380-76a9-11eb-86ec-9c4c07e01cbb.png)

**Comment by gleitz** [comment]
fstring and pathlib are done, nothing else really applies here (for now)
