### ISSUE TITLE
Standardized Logging

### ISSUE THREAD

**Issue by gleitz** [gleitz/howdoi#334]
- Standardize the way that errors are logged and reported to the user
- Get rid of `_print_err` and use something standard
- Verbosity level can then be controlled by command line flags
- `Explainability` can perhaps be sent to standard error? Is this a common practice or should it go to standard out.

**Comment by gmelodie** [comment]
Related to #330

**Comment by atodorov** [comment]
@gleitz do you mind assigning this to MLH fellow @KimaruThagna

**Comment by gleitz** [comment]
Yes, please! Thanks @KimaruThagna

**Comment by KimaruThagna** [comment]
Taken it up. Will revert with ideas and work done

**Comment by gleitz** [comment]
Proposed PR: https://github.com/gleitz/howdoi/pull/381
