### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by gleitz** [gleitz/howdoi#336]
https://github.com/psf/black ?

**Comment by npalladium** [comment]
I am a happy user of black. But playing the devil's advocate, this [write-up](https://wemake-python-stylegui.de/en/latest/pages/usage/integrations/auto-formatters.html) and this [issue](https://github.com/psf/black/issues/1178) might be informative before taking this decision.

**Comment by gleitz** [comment]
Yes I agree it's probably overkill to use black. I like the linters we have in place, but it would be good to configure a pre-commit hook or script that one can run to make sure all the linting rules pass.
