### ISSUE TITLE
Sanity check if howdoi still works and try to automatically fix it via bot

### ISSUE THREAD

**Issue by atodorov** [gleitz/howdoi#337]
Related to the recent troubles with Google changing their class names and the code not being able to find any results:

- [ ] Add a sanity check that will verify that howdoi still works, something like `howdoi <...>` & assert on the result will work
- [ ] Integrate said check into CI. IIRC GitHub Actions can be triggered periodically via cron. This will serve as an early warning system. If it fails maintainers and everyone subscribed on the repository will receive a notification.
- [ ] Follow up with some code which tries to find the correct class names, could be a script initially. 
- [ ] Instrument said script to open pull requests via the GitHub API, some examples on http://atodorov.org/blog/2015/12/01/commit-a-file-with-the-github-api-and-python/, the PyGithub library probably already contains better interface to this
- [ ] If we think we trust the steps above (or if we see that they are OK the majority of the time) then implement them as an auto-fix bot of sorts: sanity test fails => runs the fixer script => opens a PR => if PR passes we could have some automation to merge the changes. 
- [ ] All of this can be hooked into GitHub Actions as a custom action instead of having to host it somewhere.

**Comment by gleitz** [comment]
@SaurusXI we can probably start with a cron (once a day?) for all three engines (bing, duckduckgo, and google) with some sort of alerting (email?) that lets us know of a failure.
