### ISSUE TITLE
Searching of query > howdoi print in python does`t work but using "howdoi print in pythonn" works 

### ISSUE THREAD

**Issue by HussainMadarwala53** [gleitz/howdoi#338]
![howdoi](https://user-images.githubusercontent.com/70691828/108597218-e85ede80-73ad-11eb-9da8-7cc04d90eb7d.PNG)

**Comment by gleitz** [comment]
Would you let me know what version you're using with `-v` and also try clearing the cache with `-C` and letting me know if that fixes the query? 

We've been having a bit of trouble with Google so you may also want to try `-e bing` to see if those results are better until we can fix the Google issue in the next release.

**Comment by gleitz** [comment]
This should be fixed in version 2.0.13

**Comment by HussainMadarwala53** [comment]
Great, Thank you so much.
