### ISSUE TITLE
Sorry, couldn't find any help with that topic?

### ISSUE THREAD

**Issue by rajasekharponakala** [gleitz/howdoi#339]
every QUERY results in the same: Sorry, couldn't find any help with that topic?

anything wrong?

**Comment by gleitz** [comment]
Please try these steps and let me know if using a different engine works for you. 

https://github.com/gleitz/howdoi/issues/338#issuecomment-782690824

**Comment by gleitz** [comment]
This has been fixed in 2.0.13. Please update and let me know if you're having and issues.
