### ISSUE TITLE
Being able to run all the linters before code is pushed

### ISSUE THREAD

**Issue by gleitz** [gleitz/howdoi#347]
Often PRs will fail a `pylint` or `flake8` check, but you don't know it will fail unless you have your editor configured to `howdoi`'s standards. It would be nice to be able to do something like `python setup.py lint` and make sure everything is working properly.

**Comment by atodorov** [comment]
Some examples, hints:
https://github.com/PyCQA/pylint-django#installation
https://jichu4n.com/posts/how-to-add-custom-build-steps-and-commands-to-setuppy/

**Comment by gleitz** [comment]
Could also run as a pre-commit hook:
https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
https://rednafi.github.io/digressions/python/2020/04/06/python-precommit.html

**Comment by gleitz** [comment]
Fixed by https://github.com/gleitz/howdoi/pull/392
