### ISSUE TITLE
Configuration hierarchy

### ISSUE THREAD

**Issue by gleitz** [gleitz/howdoi#348]
There are environment variables, command line flags, and possible in the future a `.howdoi`. How shall we manage the hierarchy of configuration?

**Comment by npalladium** [comment]
I'm a newcomer to this project, but isn't it usually in the following descending order of preference (those earlier in the list override the ones that come later)?

1. Commandline flags
2. Environment variables
3. Local `.howdoi` file, if any
4. Global `.howdoi` file

**Comment by gleitz** [comment]
Closing as we fixed the conflicts between the environment variables and the command line flags, witht he latter taking preference as you reocmmended.
