### ISSUE TITLE
Cache is not cleared on new release

### ISSUE THREAD

**Issue by gleitz** [gleitz/howdoi#355]
All calls to the cache should use `_get_cache_key` so that `__version__` is appended.

`_get_answer` and `_get_links_with_cache` do not currently use it.

**Comment by gleitz** [comment]
One option is the take a name parameter into `_get_cache_key`. Or, we can use `inspect` module to get the calling function.

Would be good to know the speed implication of using inspect.

cc @SaurusXI

**Comment by gleitz** [comment]
Here is the blog post @atodorov mentioned http://atodorov.org/blog/2015/11/29/inspecting-method-arguments-in-python/

**Comment by atodorov** [comment]
Quick & dirty example: 

```
import inspect

def get_cache_key():
    frame = inspect.currentframe()
    # index 0 is the current function, 1 is the immediate caller in the Traceback
    caller = inspect.getouterframes(frame)[1]

    caller_name = caller.frame.f_code.co_name 
    arguments = caller.frame.f_locals

    print("    caller is", caller_name, arguments)
    return

def sayHello(name):
    get_cache_key()
    print(f"Hello {name}")

def calculate(a, b, c=0):
    get_cache_key()
    return a + b + c


sayHello("Alex")
calculate(1, 2)

sayHello("Ben")
calculate(1, 2, 3)
```


There is also `inspect.getframeinfo` where we can use `info.function` as the caller function name. I didn't dig deep into the details to figure out the difference.
