### ISSUE TITLE
Features : add tag keyword

### ISSUE THREAD

**Issue by arita37** [gleitz/howdoi#369]
Example

howdoi  @google   create a dictionnary in java

howdoi  @stack   create a dictionnary in python

howdoi  @custom   create a dictionnary

@XXX :
    Custom location for information search

**Comment by gmelodie** [comment]
I actually like that very much, a bit like DuckDuckGo's bangs: `google this string !g`. @gleitz what do you think?

**Comment by gleitz** [comment]
Rather than trying to support a bunch of tags, we might want to document and encourage the usage of aliases that can be easily configured by users. For example you can search other StackExchange properties like this:

```
alias hcook='function hcook(){ HOWDOI_URL=cooking.stackexchange.com howdoi $* ; }; hcook'
hcook make pesto
```

or make a bing-specific search like so:

```
alias hbing='function hbing(){ howdoi --engine bing $* ; }; hbing'
hbing format date bash
```
