### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by gleitz** [gleitz/howdoi#379]
As `howdoi` grew, so did the kind of error messages, exceptions, and corner cases. It would be nice to move from bubbling error responses up through various functions to throwing and catching errors.

Perhaps we can take some learnings from https://clig.dev/#errors

**Comment by jplourenco1** [comment]
I am a beginner developer looking for a project to contribute, if you give me some pointers or more examples on how these error handling functions should look, I would be happy to help.

**Comment by gleitz** [comment]
There are 4 different ways we return data to the user:

- print statements
- logging info and error
- Building a response object `res = {'error': message}` and then threading this response thru `_parse_cmd` and `_format_answer` which is then printed in the main `howdoi` function.
- raising errors like BlockError

It becomes confusing to know which you should use where, and also the thrown errors are not caught.

A good place to start would be handling the BlockError here https://github.com/gleitz/howdoi/blob/master/howdoi/howdoi.py#L622

**Comment by jplourenco1** [comment]
You say doing like https://github.com/gleitz/howdoi/blob/f6678a3f734c2159504c5f408ebe615e182b99e3/howdoi/howdoi.py#L279  but in the howdoi() function?

**Comment by gleitz** [comment]
This is pseudocode but an interesting way to catch the BlockError would be the following. We can also take action, like retrying with another search engine https://github.com/gleitz/howdoi/issues/407 that @ShezaMunir suggested.

```
    try:
        res = _get_answers(args)
        if not res:
            message = 'Sorry, couldn\'t find any help with that topic'
            if not args['explain']:
                message = f'{message} (use --explain to learn why)'
            res = {'error': message}
        cache.set(cache_key, res)
    except (RequestsConnectionError, SSLError):
        res = {'error': f'Unable to reach {args["search_engine"]}. Do you need to use a proxy?\n'}
    except BlockError:
        if args['search_engine'] == 'google':
            return
        logging.error('Retrying search with google')
        args['search_engine'] = 'google'
        return howdoi(args)
        ```

**Comment by gleitz** [comment]
The goal would be to catch all errors that might be thrown by howdoi (you can look through for all the calls to `raise`) so we get nice clean output for the user.

**Comment by ykskks** [comment]
Hello, I would like to work on this, but it looks like it's already implemented?

**Comment by ykskks** [comment]
ah I just saw #407 thank you.
