### ISSUE TITLE
Figure out how to agree to search engine terms and conditions

### ISSUE THREAD

**Issue by gleitz** [gleitz/howdoi#382]
We would like to be able to bypass the acceptance of terms and conditions seen here that sometime appear when making queries (probably for the first time?)

![Screen Shot 2021-04-17 at 8 46 01 PM](https://user-images.githubusercontent.com/8268223/115123777-df117d00-9fbe-11eb-8778-ec40a5608ee5.png)
![Screen Shot 2021-04-17 at 8 46 42 PM](https://user-images.githubusercontent.com/8268223/115123781-e20c6d80-9fbe-11eb-9561-409060a15659.png)

_Originally posted by @hieuhc in https://github.com/gleitz/howdoi/issues/372#issuecomment-821870302_

**Comment by kingpitka** [comment]
Hey, I think I solved this? My pull request fixes it for me, all that needed to be done was attaching a small "CONSENT" cookie onto the request that we were sending.
