### ISSUE TITLE
It's always error: Sorry, couldn't find any help with that topic

### ISSUE THREAD

**Issue by BaseMax** [gleitz/howdoi#384]
Hello;

Installing from package manager, I guess its version is a bit old!

root# apt install howdoi

root# howdoi --version
```
1.1.9
```

root# howdoi format date bash
```
Sorry, couldn't find any help with that topic
```

root# howdoi format
```
Sorry, couldn't find any help with that topic
```

root# howdoi format -c
```
Sorry, couldn't find any help with that topic
```

root# howdoi i am
```
Sorry, couldn't find any help with that topic
```

root# howdoi i
```
Sorry, couldn't find any help with that topic
```

root# howdoi i stupid
```
Sorry, couldn't find any help with that topic
```

root# howdoi format date bash
```
Sorry, couldn't find any help with that topic
```

root# howdoi print stack trace python
```
Sorry, couldn't find any help with that topic
```

root# howdoi create tar archive
```
Sorry, couldn't find any help with that topic
```

**Comment by gleitz** [comment]
Thanks for the note. Unfortunately I don't control that package manager version, but you're welcome to submit the big report to them. 

Please use pip to install howdoi.
