### ISSUE TITLE
Add an issue template that encourages people to submit bugs with `--explain`

### ISSUE THREAD

**Issue by gleitz** [gleitz/howdoi#385]
It will be very helpful.

**Comment by mwizasimbeye11** [comment]
Maybe I can help with this, can you explain more?

**Comment by gleitz** [comment]
Hi Mwiza! Hope you're well.

When folks submit bugs they often simply submit the query they were using that failed, e.g. `howdoi format date bash` and then some stack trace or response.

It would be better if all bug reports requested that they be submitted along with a `--explain` so we can understand where the problem is coming from. 

I think this could be done with a Github template that included a note about requiring that the `--explain` be submitted along with any bug report.

I thinky you can try this out in your own repo with these instructions: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

**Comment by mwizasimbeye11** [comment]
Great, so to clarify on the github issue.
The --explain flag has already been implemented and whats needed is a github template to submit issues that contain the query, stacktrace and the --explain output?

**Comment by gleitz** [comment]
Yes. Here is a good example -> https://github.com/gleitz/howdoi/issues/386

**Comment by mwizasimbeye11** [comment]
Alright great, thanks. Clear now. Working on this.. 
Also any additional issues that might need attention, let me know.

**Comment by SaurusXI** [comment]
@gleitz is this being worked on? I'd love to contribute again :)

**Comment by gleitz** [comment]
Example:

```
Issue:

Output of using `--explain`:
```

**Comment by gleitz** [comment]
@SaurusXI you can take it if you like! It would be cool to get some kind of a starter text populated for when folks submit issues.

**Comment by SaurusXI** [comment]
awesome, I'll work on this then
