### ISSUE TITLE
Random TypeError

### ISSUE THREAD

**Issue by Tiger-The-Cat** [gleitz/howdoi#386]
I just started using howdoi, I have not modified it in any way.
![image](https://user-images.githubusercontent.com/70044734/116914813-18bdc700-ac00-11eb-84d5-d19e1a61b1c7.png)

**Comment by gleitz** [comment]
Would you please post the output of the `--explain` command?

If this is on Windows, you might be using an older version. The latest version is 2.0.15

**Comment by Tiger-The-Cat** [comment]
I just installed howdoi today, and pip says that my howdoi version is 2.0.15.
![image](https://user-images.githubusercontent.com/70044734/116914250-55d58980-abff-11eb-85fd-d264a873506e.png)

**Comment by gleitz** [comment]
Thanks!

It looks like the link that is recommended doesn't actually have any valid answers -> https://stackoverflow.com/questions/30616542/how-to-do-i-get-the-status-of-satellites-i-e-alive-or-dead-while-flight-is-in-a

I think this is one of the first times we've seen this. The fix will be to handle that edge case.

You can ask for the answer is position #2, which I believe does return an answer:

```
» howdoi access satellites -p2 --explain
INFO: Version: 2.0.15
INFO: Fetching answers for query: access satellites
INFO: Using cached links
INFO: stackoverflow.com links found on google: 1
INFO: Answers requested: 1, Starting at position: 2
INFO: Total answers returned: 1
There is no public available API that allows you to get this kind of detailed information about the GPS satellites.
```

**Comment by Tiger-The-Cat** [comment]
Okay, thank you!

**Comment by gleitz** [comment]
Re-opening so we can remember that this has to be fixed.

Not sure exactly what you're looking for, but I build a project called [Symphony of Satellites](https://github.com/gleitz/spheremusic) that used [Celestrak](http://celestrak.com/) to fetch the satellite data.

Happy hacking!

**Comment by Tiger-The-Cat** [comment]
Celestrak was just what I was looking for! Thank you!
