### ISSUE TITLE
More issue templates

### ISSUE THREAD

**Issue by gmelodie** [gleitz/howdoi#399]
It'd be good to have more templates for issues (as of now we only have a bug report one). I think a good ones to have are: 
1. Question
2. Feature request
3. Bug report (already existent, but might need to be reviewed)

**Obs:** There's even an [awesome list](https://github.com/devspace/awesome-github-templates) for github templates!

**Comment by gleitz** [comment]
Fixed in https://github.com/gleitz/howdoi/pull/406
