### ISSUE TITLE
remove Python2 support in command_line_runner

### ISSUE THREAD

**Issue by ykskks** [gleitz/howdoi#426]
### Description 
README.md says,
> Unfortunately Python 2.7 support has been discontinued :(

I think we can drop support for the older version of Python [here](https://github.com/gleitz/howdoi/blob/f19ca79c7aff69e09c5393b2ede6ab24cddf6f75/howdoi/howdoi.py#L816).

I am not sure if we still need utf-8 encoding.
Maybe we can do like this?

```
utf8_result = howdoi(args).encode('utf-8', 'ignore')
sys.stdout.buffer.write(utf8_result)

# or
result = howdoi(args)
print(result)
```

### Have you read the Contributing Guidelines on Pull Requests on mkdocs?

Yes

**Comment by gleitz** [comment]
Yes, that sounds like a good change!

**Comment by ykskks** [comment]
Thank you. I will submit a PR!

**Comment by ykskks** [comment]
I forked master and clone into local. Then I ran tests without any change to code. I get one failure but have no idea whats causing it. Can someone help me out?

```
======================================================================
FAIL: test_missing_pre_or_code_query (__main__.HowdoiTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/XXX/Projects/howdoi/test_howdoi.py", line 270, in test_missing_pre_or_code_query
    self.assertIn('XML elements present in a XML', output)
AssertionError: 'XML elements present in a XML' not found in '<people>\n    <student>\n        <name>John</name>\n    </student>\n</people>\n'

----------------------------------------------------------------------
```

**Comment by ykskks** [comment]
Looks like the top answer to the test query changed, which is causing the test to fail.

See the link: https://stackoverflow.com/questions/15920496/difference-between-element-node-and-text-node

**Comment by gleitz** [comment]
I had this problem as well! The tests seem to run properly when I open a PR, but locally they do not run. 

I was wondering if somehow the `page_cache` is not being used when running the test locally.

**Comment by ykskks** [comment]
@gleitz 
I submitted a PR #427.

I will work on `page_cache` problem in another issue!
