### ISSUE TITLE
Pylint passes locally but fails in Github actions

### ISSUE THREAD

**Issue by gleitz** [gleitz/howdoi#434]
#### What happened:

Check out https://github.com/gleitz/howdoi/pull/433/checks?check_run_id=3861232824

The pylint tests fail in Github actions but pass locally (with the same version of pylint).

Locally:

```
» python setup.py lint
running lint

Running Flake8...
No lint errors found by Flake8

Running Pylint...

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

No lint errors found by Pylint

» pylint --version
pylint 2.11.1
astroid 2.8.0
Python 3.9.7 (default, Sep 20 2021, 08:30:41)
[Clang 12.0.0 (clang-1200.0.32.29)]
```

**Comment by Prateek93a** [comment]
The `pre-commit` is configured to use `pylint 2.8.2` which does not give error but `pylint 2.11.1` gives the error. You can try it by running ` pylint howdoi --rcfile=.pylintrc`.

Can you check the output of `which pylint` to see if it from your virtual environment or the global one?

**Comment by gleitz** [comment]
I think we should do three things: 

- Unify the version of Pylint (2.11.1)
- Make sure that all pylint command use `pylint howdoi *.py --rcfile=.pylintrc`
- Pin the version of pylint used by the github action

@V2dha
