### ISSUE TITLE
VS code extension using GPT for rendering correct code

### ISSUE THREAD

**Issue by joeyouss** [gleitz/howdoi#435]
### Description 
Future goals - VScode extension for howdoi which sources any comment in the code starting with howdoi and then automatically calls the howdoi function and gives/writes the code using GPT pre-trained models

Current goals -  VScode extension for howdoi which sources any comment in the code starting with howdoi and then automatically calls the howdoi function and gives the code from the internet : instead of in Command line , in the codespace itself.

**Comment by gleitz** [comment]
Tools like [copilot](https://github.com/features/copilot) are likely better if you're looking for AI-assisted code support. When I'm looking for best practices that are peer-reviewed, I use howdoi. Using them together likely gives you the best of both worlds.
