### ISSUE TITLE
Add terminal support for images 

### ISSUE THREAD

**Issue by V2dha** [gleitz/howdoi#437]
### Description 
Some of the answers returned from the query contains image links in them like the one mentioned below.

![Capture](https://user-images.githubusercontent.com/50369708/137757585-0b8c3a6f-c96f-4c7f-adde-0481069c173c.PNG)

The quality of the answer can be improved if there is a way to incorporate the image URLs in the answers by adding a terminal support for images or if not possible opening the image URLs identified on the browser locally.

### Additional Comments (if any)
This is the original StackOverflow answer from where the answer snippet was extracted with the image.

![Capture](https://user-images.githubusercontent.com/50369708/137758203-3d73ebda-99c7-4d52-9645-e62062d35017.PNG)

### Have you read the Contributing Guidelines on Pull Requests on mkdocs?
Yes

**Comment by gleitz** [comment]
Yes I like the idea, but in practice it sounds a little sketchy. The whole reason I made howdoi was to stay out of the browser. If you really need an image you can get the link with `-l` and pipe to `xargs open` to get in the browser.

```
howdoi open wsl folder in windows -l | xargs open
```

**Comment by V2dha** [comment]
I agree with the misuse part. So as an alternative what if we could fetch the alt text specified in the image tag? It would at least give a description of the image. Although I don't think most of the time while uploading an image the alt attribute is filled in.
