### ISSUE TITLE
Is the tracking parameter t=hj in the duckduckgo URL intentional?

### ISSUE THREAD

**Issue by Alexhans** [gleitz/howdoi#465]
Hi,

I was looking at the different query parameters in the search urls when I found that duckduckgo's `t` is a tracking code (I don't know what `hj` as the value means:
https://help.duckduckgo.com/privacy/t/

> Through [partnerships](https://help.duckduckgo.com/duckduckgo-help-pages/company/partnerships) with developers and companies, DuckDuckGo has been integrated into many applications. In these partnerships, a portion of DuckDuckGo's advertising revenue is sometimes shared back. To assign advertising revenue and collect anonymous aggregate usage information, developers add a unique "&t=" parameter to searches made through their applications.

https://github.com/gleitz/howdoi/blob/f202eea521be7c280390a950fc881cce59336ceb/howdoi/howdoi.py#L72

**Comment by gleitz** [comment]
I'm not sure if it is necessary or not, but currently duckduckgo is not working as an engine due to https://github.com/gleitz/howdoi/issues/404

**Comment by gleitz** [comment]
If you'd like to figure out that issue, I could use some help with it!

**Comment by Alexhans** [comment]
I can try.  I actually came across this while quickly playing around to see If I could [add brave support.](https://github.com/gleitz/howdoi/compare/master...Alexhans:howdoi:brave)

Support works but I wanted to understand the decisions around URLs and usage.  I did get temporarily blocked when I added the unit tests in brave which it's somewhat expected (I still remember the [Google has been DDoSing SourceHut for over a year](https://drewdevault.com/2022/05/25/Google-has-been-DDoSing-sourcehut.html) story).

The only thing I can think of is ask duckduckgo & brave to see if they have specific ways to interact programmatically with their websites.  

I do think the answer will not be satisfactory for duckduckgo since, in [their instant answers api page](https://duckduckgo.com/api) they state:

> This API does not include all of our links, however. That is, it is not a full search results API or a way to get DuckDuckGo results into your applications beyond our instant answers. Because of the way [we generate our search results](https://help.duckduckgo.com/results/sources), we unfortunately do not have the rights to fully syndicate our results, free or paid. For the same reason, we cannot allow framing our results without our branding. Please see [our partnerships page](https://help.duckduckgo.com/company/partnerships) for more info on guidelines and getting in touch with us.

So crawling ethically (Without trying to circumvent through proxies or similar) will invariably get blocked. For DDG, it might be a case of choosing whether to remove it entirely or just support instant answers through their API (For any API based access, users could get their own tokens like in [OpenBBTerminal](https://github.com/OpenBB-finance/OpenBBTerminal)

**Comment by gleitz** [comment]
Yes I am not optimistic that API access will be given, so we're left with crawling.

I also get rate limited during development, which is why I have the [caching mechanism](https://github.com/gleitz/howdoi/blob/master/test_howdoi.py#L48) in place when running tests.

**Comment by gleitz** [comment]
I didn't know brave had a search engine. I would accept that PR if you want to open it.

**Comment by Alexhans** [comment]
I'll take a look at what we discussed over the weekend and create the pull request.  It's been a busy period.

**Comment by gleitz** [comment]
No worries - take your time and thanks again for any support you can give to the project.
