### ISSUE TITLE
Function `_format_url_to_filename` only used in tests

### ISSUE THREAD

**Issue by vbuxbaum** [gleitz/howdoi#466]
### Description 

I was studying the codebase, and found out that the function `_format_url_to_filename` in file `howdoi/howdoi.py` is defined but used only in tests.

The proposal here is to move this function from its current file to `test_howdoi.py`.

### Have you read the Contributing Guidelines on Pull Requests on mkdocs?

(Write your answer here.)

**Comment by vbuxbaum** [comment]
Hi @gleitz! Hope you are doing fine

Since this is a simple refactoring issue, can I be assigned to it?

**Comment by gleitz** [comment]
Sure thing!
