### ISSUE TITLE
Add checks when it comes to something like `range`

### ISSUE THREAD

**Issue by CaedenPH** [gleitz/howdoi#471]
### Description 
Add a `range` check. For example, it makes logical sense that you can't have a valid question under 2 characters long, and probably above 150 either. 

### Additional Comments (if any)
```bash
~ howdoi e
e
~ howdoi e --explain
INFO: Version: 2.0.20
INFO: Fetching answers for query: e
INFO: Using cached links
INFO: Links from stackoverflow.com found on google: 1
INFO: URL: https://stackoverflow.com/questions/71039088/what-is-onchange-e-setnamee-target-value-in-react-mean
INFO: Answers requested: 1, Starting at position: 1
INFO: Using cached page: https://stackoverflow.com/questions/71039088/what-is-onchange-e-setnamee-target-value-in-react-mean
INFO: Total answers returned: 1
```
This is what happens when you run `e`... Questionable behavious

### Have you read the Contributing Guidelines on Pull Requests on mkdocs?
Yes

**Comment by gleitz** [comment]
I would be happy to accept a PR that limits the query to >=2 characters long.

**Comment by renatocfrancisco** [comment]
@CaedenPH 
![8pmbgp](https://github.com/gleitz/howdoi/assets/56325092/92bc63e3-1a3b-47a1-9fb8-702d2cb24cb5)

Also, close issue?
