### ISSUE TITLE
Change pull request template "Pull request Type" to checklist

### ISSUE THREAD

**Issue by CaedenPH** [gleitz/howdoi#475]
### Description 
Change the pull request type to a checklist for ease of access
![image](https://user-images.githubusercontent.com/23421705/195186239-0653e701-5fde-409a-b3c2-0d978a0d2d2e.png)
![image](https://user-images.githubusercontent.com/23421705/195186435-fa78ca23-2092-4add-b2f8-f854e6e5e65d.png)

### Have you read the Contributing Guidelines on Pull Requests on mkdocs?
Yes

**Comment by gleitz** [comment]
I wish dropdown was an option in markdown

**Comment by gleitz** [comment]
I would accept a pull request. You will want to change the markdown on https://github.com/gleitz/howdoi/blob/master/.github/PULL_REQUEST_TEMPLATE.md
