### ISSUE TITLE
Add page cache to .gitignore

### ISSUE THREAD

**Issue by CaedenPH** [gleitz/howdoi#476]
### Description 
Add `page_cache/` directory to `.gitignore`

### Additional Comments (if any)
When making tests, you create files in the `page_cache` directory, and these are then counted as untracked
![image](https://user-images.githubusercontent.com/23421705/195186853-9f87d954-42eb-42fc-a718-a53e80fda237.png)

### Have you read the Contributing Guidelines on Pull Requests on mkdocs?
Yes

**Comment by gleitz** [comment]
Please check in those files. The page cache is used by the test runner to avoid being rare limited by the search engines. Thx!
