### ISSUE TITLE
Fetch Bing- Chat-GPT

### ISSUE THREAD

**Issue by arita37** [gleitz/howdoi#483]
Bing Search provides GPT-4 answers,
it will be good to fetch them as answers.

Can you explain what kind of changes needed ?

I will be happy to do a PR.

**Comment by gleitz** [comment]
It might be a little tricky. I think that Bing and ChatGPT would require API keys to access. I'm also a little reluctant to return AI generated answers. According to [this article](https://meta.stackoverflow.com/questions/421831/temporary-policy-chatgpt-is-banned):

```
...because the average rate of getting correct answers from ChatGPT is too low, the posting of answers created by ChatGPT is substantially harmful to the site and to users who are asking and looking for correct answers.
```

I think I would prefer to continue to return answers from StackOverflow, but perhaps in the future AI generated answers will be allowed on that site (which can then be peer reviewed by users).
