### ISSUE TITLE
queries keep resulting in "Sorry, couldn't find any help with that topic"

### ISSUE THREAD

**Issue by monfresh** [gleitz/howdoi#54]
I've been trying to use howdoi over the past few days and I keep getting "Sorry, couldn't find any help with that topic". Did something break recently? 

None of the queries in the test file work:

format date bash
print stack trace python
convert mp4 to animated gif
create tar archive

**Comment by rdxmb** [comment]
I have just installed version 1.1.9 via apt and face the same problem. Just tried to install via pip3 and it's the same.

**Comment by gleitz** [comment]
The apt version is definitely very old, but the pip3 version should be up to date. Would you mind trying my suggestion here -> https://github.com/gleitz/howdoi/issues/372#issuecomment-819625100 and posting the result in that thread?

**Comment by rdxmb** [comment]
done

**Comment by Agustin627** [comment]
hello I was trying with this "python3 -m howdoi format date bash --explain -C~" and it throws me the following error: usage: __main__.py [-h] [-p POS] [-n NUM] [-a] [-l] [-c] [-x] [-C] [-j] [-v] [-e [ENGINE]] [--save] [--view] [--remove] [--empty ]
                    [QUERY...]
__main__.py: error: argument -C/--clear-cache: ignored explicit argument '~'

**Comment by gleitz** [comment]
Looks like you need to remove the `~` at the end
